// AsyncConstants
export const authToken = 'authToken';
export const token_details = 'token_details';
export const QB_Auth_Password = 'qbPassword';
export const Google_API_Key = 'AIzaSyCfHXf6aHFVbGZTCLl-Vte3YjyUQa-AFZ4';
export const publishableKey = 'pk_test_ArfgYsDvhFEnPImjf2QHH5YH00ozgvzrTO';
export const resgisterMerchantURL = 'https://connect.stripe.com/express/oauth/authorize';

export const firebaseConfig = {
  apiKey: 'AIzaSyDgnt9jN8EbVwRPMClVf3Ac1tYQKtaLdrU',
  authDomain: 'townscup-fee6e.firebaseapp.com',
  databaseURL: 'https://townscup-fee6e.firebaseio.com',
  projectId: 'townscup-fee6e',
  storageBucket: 'townscup-fee6e.appspot.com',
  messagingSenderId: '1003329053001',
  appId: '1:1003329053001:web:f079b7ed53716fa8463a98',
  measurementId: 'G-N44NC0Z1Q7',
};

export const monthsSelectionData = [
  { label: 'Past 3 Months', value: 'Past 3 Months' },
  { label: 'Past 6 Months', value: 'Past 6 Months' },
  { label: 'Past 9 Months', value: 'Past 9 Months' },
  { label: 'Past 12 Months', value: 'Past 12 Months' },
]

export const gameData = {
  challenge_referee: [{ is_chief: true, responsible_team_id: 'aCqH9ixc23SSPyrwzUbNDDw3YGG3' }, { is_chief: false, responsible_team_id: 'aLaV61nfhEfmVgDKy5MAnDOtLHu1' }],
  status: 'ended',
  invited_by: 'aCqH9ixc23SSPyrwzUbNDDw3YGG3',
  actual_enddatetime: 1611639994,
  singlePlayerGame: true,
  challenge_id: '1610622565569-20',
  resume_datetime: 0,
  away_team_goal: 0,
  responsible_to_secure_venue: 'Kishan1 Makani1',
  invited_to: 'aLaV61nfhEfmVgDKy5MAnDOtLHu1',
  home_team: {
  sports: ['Carom', 'Volleyball', 'Soccer', 'Tennis'],
  entity_type: 'player',
  privacy_events: 'everyone',
  privacy_profile: 'everyone',
  customer_id: 'cus_Ig4yRniShvkCDD',
  source: 'pm_1I5oiFAgsVW5UJBh1Fes5ZMU',
  full_name: 'Kishan1 Makani1',
  state_abbr: 'BC',
  email: 'makani20+1@gmail.com',
  country: 'Canada',
  teamIds: ['e02e210f-f8fa-4811-8433-f2a5ae2ef341', '60abaa83-6b15-469e-8b50-eb66c0e54008', '5d17414d-2009-4623-8645-05dac42d8014'],
  games: [{
  sport_name: 'Tennis', sport_type: 'single', full_image: 'https://picsum.photos/id/320/640/1136', fee: '20', thumbnail: 'https://picsum.photos/id/320/100/100', totalGames: 3,
  }, {
  sport_name: 'Soccer', sport_type: 'multiplayer', full_image: 'https://picsum.photos/id/320/640/1136', thumbnail: 'https://picsum.photos/id/320/100/100', totalGames: 6,
  }],
  city: 'Vancouver',
  user_id: 'aCqH9ixc23SSPyrwzUbNDDw3YGG3',
  last_name: 'Makani1',
  group_events: true,
  signedup_user: true,
  registered_sports: [{
  sport_name: 'Tennis', Tennis: 'single-multiplayer', currency_type: 'CAD', fee: '20', language: ['English(Canada)', 'English(Singapore)'], cancellation_policy: 'strict', descriptions: 'I Love Tennis', point: 500,
  }],
  privacy_followers: 'everyone',
  first_name: 'Kishan1',
  scorekeeper_data: [{
  sport_name: 'Volleyball', certificates: [], is_published: true, fee: '10', language: [{ language_name: 'English' }, { language_name: 'English(Canada)' }, { language_name: 'English(Singapore)' }], cancellation_policy: 'strict', descriptions: 'Test desc for volleyball',
  }],
  merchant_id: 'acct_1I4guvPIoJEXON0W',
  is_following: false,
  posts_count: 0,
  follower_count: 0,
  following_count: 4,
  },
  pause_datetime: 0,
  score_rules: {
  apply_tiebreaker_in_game: true, apply_duece_in_set: true, winning_point_in_tiebreaker: 7, total_sets: 3, winning_point_in_game: 4, game_count_to_win_set: 6, tiebreaker_apply_at: 6, apply_duece_in_game: true, apply_duece_in_tiebreaker: true,
  },
  gameId: 'da7f9ff0-c5e5-40bc-a0b2-137eb1c97317',
  game_id: 'da7f9ff0-c5e5-40bc-a0b2-137eb1c97317',
  start_datetime: 1630434600,
  gameStats: [{ home_team: 2, label: 'Total point won', away_team: 0 }, { home_team: 100, label: '1st serve in %', away_team: 0 }, { home_team: 100, label: '1st serve point won %', away_team: 0 }, { home_team: 0, label: '2nd serve point won %', away_team: 0 }, { home_team: 0, label: 'Winners', away_team: 0 }, { home_team: 0, label: 'Break point won', away_team: 0 }],
  scoreboard: {
   game_inprogress: {
  's_id#g_id': '4c8986e8-12f1-48e6-b634-c2f4747ed422#7259d929-9e5e-4cab-b883-132aa16f7aff', s_id: '4c8986e8-12f1-48e6-b634-c2f4747ed422', g_id: '7259d929-9e5e-4cab-b883-132aa16f7aff', start_datetime: 1611639980, home_team_point: '30', serving_team_id: 'aCqH9ixc23SSPyrwzUbNDDw3YGG3', away_team_point: '0', 'set#game': '4c8986e8-12f1-48e6-b634-c2f4747ed422#7259d929-9e5e-4cab-b883-132aa16f7aff', timestamp: 1611639982, game_id: 'da7f9ff0-c5e5-40bc-a0b2-137eb1c97317',
  },
  sets: [{
  home_team_win_count: 0, s_id: '4c8986e8-12f1-48e6-b634-c2f4747ed422', away_team_win_count: 0, start_datetime: 1611639979, game_id: 'da7f9ff0-c5e5-40bc-a0b2-137eb1c97317', timestamp: 1611639982,
  }],
  },
  special_rule: 'did fds dad a',
  breakTime: 0,
  away_team: {
  sports: ['Soccer', 'Tennis'],
  privacy_events: 'everyone',
  full_image: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/d90c638c-97d1-4c36-9ed1-016d0f28406c',
  full_name: 'kishan makani',
  email: 'makani20@gmail.com',
  posts_count: 19,
  country: 'India',
  language: ['English', 'English(Canada)'],
  weight: '101',
  city: 'Gorakhpur',
  referee_data: [{
  sport_name: 'soccer', certificates: [{ title: 'Certificate 1', url: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/c83a2f52-9a63-4bfd-b9f8-f3b2eded085c', thumbnail: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/4ea9d480-2f26-474a-b1c4-6a1daa288160' }, { title: 'Certificate 2', url: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/9846f291-4016-4291-8ea5-d0fefd9a4c0c', thumbnail: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/55c6e436-7f1f-4520-ac84-8b16f10cd7e0' }], is_published: true, fee: '20', cancellation_policy: 'strict', language: [{ language_name: 'English' }, { language_name: 'English(Singapore)' }], descriptions: 'This is soccer ds',
  }],
  follower_count: 1,
  clubIds: ['1829e07b-db61-469d-972b-3174d340fc02'],
  signedup_user: true,
  privacy_followers: 'everyone',
  background_full_image: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/b79b4ed2-a521-4b53-9a50-3497acbf79de',
  thumbnail: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/9e138ec5-60e1-463e-9fd4-c34b89903291',
  location: 'Gorakhpur, Gujarat, India',
  entity_type: 'player',
  following_count: 3,
  privacy_profile: 'everyone',
  customer_id: 'cus_IfG8JSTJM0o2mB',
  most_used_foot: 'Pose',
  source: 'pm_1I8KEnAgsVW5UJBhaFZeDpJP',
  state_abbr: 'Gujarat',
  teamIds: ['4ad24042-d52e-42e0-b4bf-e4af4d5097a5', 'd7db702b-2f1c-4225-9595-af768915b56f'],
  gender: 'Male',
  games: [{
  sport_name: 'Tennis', sport_type: 'single', full_image: 'https://picsum.photos/id/320/640/1136', fee: '0', thumbnail: 'https://picsum.photos/id/320/100/100', totalGames: 3,
  }, {
  sport_name: 'Soccer', sport_type: 'multiplayer', full_image: 'https://picsum.photos/id/320/640/1136', fee: '0', thumbnail: 'https://picsum.photos/id/320/100/100', totalGames: 6,
  }, {
  sport_name: 'Tennis', sport_type: 'single', full_image: 'https://picsum.photos/id/320/640/1136', fee: '15', thumbnail: 'https://picsum.photos/id/320/100/100', totalGames: 3,
  }, {
  sport_name: 'Tennis Double', sport_type: 'multiplayer', full_image: 'https://picsum.photos/id/320/640/1136', fee: '10', thumbnail: 'https://picsum.photos/id/320/100/100', totalGames: 0,
  }, {
  sport_name: 'Tennis Double', sport_type: 'multiplayer', full_image: 'https://picsum.photos/id/320/640/1136', fee: '', thumbnail: 'https://picsum.photos/id/320/100/100', totalGames: 0,
  }],
  background_thumbnail: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/c4466781-2446-4610-b997-98eb79237d87',
  user_id: 'aLaV61nfhEfmVgDKy5MAnDOtLHu1',
  last_name: 'makani',
  registered_sports: [{
  sport_name: 'Tennis', homePlace: 'Gorakhpur', fee: '0', latitude: 26.7605545, ntrp: '2.5', cancellation_policy: 'strict', descriptions: 'Tennis description123', point: 530, longitude: 83.3731675,
  }, {
  sport_name: 'Soccer', homePlace: 'Gorakhpur', fee: '0', latitude: 26.7605545, ntrp: '1.0', cancellation_policy: 'strict', descriptions: 'Soccer Description', point: 530, longitude: 83.3731675,
  }, {
  sport_name: 'Tennis', currency_type: 'CAD', singlePlayerGame: false, fee: '15', language: ['English(Canada)'], cancellation_policy: 'strict', descriptions: 'I like', point: 500, sport_type: 'single-multiplayer',
  }, {
  sport_name: 'Tennis Double', currency_type: 'CAD', fee: '10', language: ['English(Canada)', 'English(Singapore)'], cancellation_policy: 'strict', descriptions: 'I Like Tennis Double', point: 500,
  }, {
  sport_name: 'Tennis Double', currency_type: 'CAD', fee: '', language: [], cancellation_policy: 'strict', descriptions: '', point: 500,
  }],
  height: '201',
  first_name: 'kishan',
  scorekeeper_data: [{
  sport_name: 'Volleyball', certificates: [{ title: 'Certificate1', url: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/c9ccee34-1466-44af-8d47-b9272dcc904b', thumbnail: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/545818a1-89fa-48b1-b22f-fd52bf53e103' }, { title: 'Certificate2', url: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/0e4e537f-57bb-47b1-b120-fcd3e318cf87', thumbnail: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/19944dbd-97df-4616-8dd2-34baa99696a7' }], is_published: true, fee: '20', cancellation_policy: 'strict', language: [{ language_name: 'English' }, { language_name: 'English(Canada)' }], descriptions: 'I am volleyball scorekeeper',
  }, {
  sport_name: 'Carom', certificates: [{ title: 'Certi1', url: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/c53e53cd-7463-400b-9b1e-6b86fa36d2a7', thumbnail: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/d347fc83-31db-4af4-b577-98b7c102164b' }], is_published: true, fee: '10', language: [{ language_name: 'English' }, { language_name: 'English(Canada)' }, { language_name: 'English(Singapore)' }], cancellation_policy: 'strict', descriptions: 'I am carom scorekeeper',
  }, {
  sport_name: 'Baseball', certificates: [], is_published: true, fee: '10', language: [], cancellation_policy: 'strict', descriptions: 'Scorekeeper of baseball',
  }, {
  sport_name: 'Soccer', certificates: [{ title: 'Certificate1', url: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/b9b7a70d-0c0c-484f-bfd2-67857d779eed', thumbnail: 'https://dev-townscup-gallery.s3.amazonaws.com/aLaV61nfhEfmVgDKy5MAnDOtLHu1/2719e10b-821f-4016-bea8-4d58b9348721' }], is_published: true, fee: '10', language: [{ language_name: 'English' }, { language_name: 'English(Canada)' }], cancellation_policy: 'strict', descriptions: 'I am scorekeeper of soccer',
  }],
  is_following: false,
  merchant_id: 'acct_1I7DzoPAlhrwm7Zy',
  description: 'I am beard man',
  currency_type: 'USD',
  phone_numbers: [{ country_code: 'Canada(+1)', phone_number: '1111111111' }],
  birthday: 1423420200,
  },
  referees: [{
  chief_referee: true,
  referee_id: 'k9Ybsfd39hX3UAF1okasz2UqP3g1',
  booked_by: 'aLaV61nfhEfmVgDKy5MAnDOtLHu1',
  reservation: {
  expiry_datetime: 1611631951,
  service_fee1: {
  refundable: 'conditional', fee_type: 'percentage', stripe_fee: 50, minimum: 1, fee: 8, order: 0,
  },
  service_fee2: {
  refundable: 'conditional', fee_type: 'percentage', stripe_fee: 50, minimum: 1, fee: 2.5, order: 0,
  },
  created_by: { uid: 'aLaV61nfhEfmVgDKy5MAnDOtLHu1', first_name: 'kishan', last_name: 'makani' },
  status: 'accepted',
  accumlated_strip_fee: 1.3,
  payment_failure_logs: [{
   message: 'Your card was declined.',
  object: {
  doc_url: 'https://stripe.com/docs/error-codes/card-declined',
  headers: {
  date: 'Thu, 21 Jan 2021 03:33:25 GMT', server: 'nginx', 'content-length': '8288', 'x-stripe-c-cost': '21', 'request-id': 'req_DOZnUV2VhOulQN', 'stripe-version': '2020-03-02', 'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE', 'strict-transport-security': 'max-age=31556926; includeSubDomains; preload', 'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-max-age': '300', 'content-type': 'application/json', connection: 'keep-alive', 'cache-control': 'no-cache, no-store',
  },
  rawType: 'card_error',
  code: 'card_declined',
  charge: 'ch_1IBtvEAgsVW5UJBhhqHteeMr',
  requestId: 'req_DOZnUV2VhOulQN',
  decline_code: 'generic_decline',
  raw: {
  doc_url: 'https://stripe.com/docs/error-codes/card-declined',
  headers: {
  date: 'Thu, 21 Jan 2021 03:33:25 GMT', server: 'nginx', 'content-length': '8288', 'x-stripe-c-cost': '21', 'request-id': 'req_DOZnUV2VhOulQN', 'stripe-version': '2020-03-02', 'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE', 'strict-transport-security': 'max-age=31556926; includeSubDomains; preload', 'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-max-age': '300', 'content-type': 'application/json', connection: 'keep-alive', 'cache-control': 'no-cache, no-store',
  },
  charge: 'ch_1IBtvEAgsVW5UJBhhqHteeMr',
  code: 'card_declined',
  decline_code: 'generic_decline',
  requestId: 'req_DOZnUV2VhOulQN',
  payment_intent: {
  metadata: { reservation_id: '1610622661093-86' },
  livemode: false,
  canceled_at: null,
  amount_capturable: 0,
  description: null,
  source: null,
  statement_descriptor: null,
  transfer_data: { destination: 'acct_1I7YPZPJ2sxoFK8x' },
  shipping: null,
  review: null,
  currency: 'cad',
  id: 'pi_1IBtvEAgsVW5UJBhvbuugmlS',
  client_secret: 'pi_1IBtvEAgsVW5UJBhvbuugmlS_secret_xWLuPSJLphSETACG7k9Ul9a9x',
  payment_method_options: { card: { installments: null, request_three_d_secure: 'automatic', network: null } },
  payment_method: null,
  capture_method: 'automatic',
  amount: 1221,
  transfer_group: null,
  on_behalf_of: 'acct_1I7YPZPJ2sxoFK8x',
  created: 1611200004,
  payment_method_types: ['card'],
  amount_received: 0,
  setup_future_usage: null,
  confirmation_method: 'automatic',
  cancellation_reason: null,
  charges: {
  has_more: false,
  data: [{
  balance_transaction: null,
  billing_details: {
  name: null,
  address: {
  country: null, state: null, postal_code: '123123', city: null, line2: null, line1: null,
  },
  phone: null,
  email: null,
  },
  metadata: { reservation_id: '1610622661093-86' },
  livemode: false,
  destination: 'acct_1I7YPZPJ2sxoFK8x',
  description: null,
  failure_message: 'Your card was declined.',
  fraud_details: {},
  source: null,
  amount_refunded: 0,
  refunds: {
  has_more: false, data: [], total_count: 0, url: '/v1/charges/ch_1IBtvEAgsVW5UJBhhqHteeMr/refunds', object: 'list',
  },
  statement_descriptor: null,
  transfer_data: { destination: 'acct_1I7YPZPJ2sxoFK8x', amount: null },
  receipt_url: null,
  shipping: null,
  review: null,
  captured: false,
  calculated_statement_descriptor: 'VINEET PATIDAR',
  currency: 'cad',
  refunded: false,
  id: 'ch_1IBtvEAgsVW5UJBhhqHteeMr',
  outcome: {
  reason: 'generic_decline', risk_level: 'normal', seller_message: 'The bank did not return any further details with this decline.', network_status: 'declined_by_network', type: 'issuer_declined', risk_score: 27,
  },
  payment_method: 'pm_1I6DFcAgsVW5UJBhkPoBwOcz',
  order: null,
  dispute: null,
  amount: 1221,
  disputed: false,
  failure_code: 'card_declined',
  transfer_group: 'group_pi_1IBtvEAgsVW5UJBhvbuugmlS',
  on_behalf_of: 'acct_1I7YPZPJ2sxoFK8x',
  created: 1611200004,
  payment_method_details: {
   type: 'card',
  card: {
  country: 'US', last4: '0341', funding: 'credit', checks: { address_postal_code_check: 'pass', address_line1_check: null, cvc_check: null }, wallet: null, installments: null, fingerprint: 'pOLCnAkGISuK8bjb', exp_month: 1, exp_year: 2022, three_d_secure: null, brand: 'visa', network: 'visa',
  },
  },
  amount_captured: 0,
  source_transfer: null,
  receipt_number: null,
  application: null,
  receipt_email: null,
  paid: false,
  application_fee: null,
  payment_intent: 'pi_1IBtvEAgsVW5UJBhvbuugmlS',
  invoice: null,
  statement_descriptor_suffix: null,
  application_fee_amount: 182,
  object: 'charge',
  customer: 'cus_IfG8JSTJM0o2mB',
  status: 'failed',
  }],
  total_count: 1,
  url: '/v1/charges?payment_intent=pi_1IBtvEAgsVW5UJBhvbuugmlS',
  object: 'list',
  },
  application: null,
  receipt_email: null,
  last_payment_error: {
  doc_url: 'https://stripe.com/docs/error-codes/card-declined',
  charge: 'ch_1IBtvEAgsVW5UJBhhqHteeMr',
  code: 'card_declined',
  decline_code: 'generic_decline',
  message: 'Your card was declined.',
  type: 'card_error',
  payment_method: {
  billing_details: {
  name: null,
  address: {
  country: null, state: null, postal_code: '123123', city: null, line2: null, line1: null,
  },
  phone: null,
  email: null,
  },
  metadata: { test_key: 'test_value' },
  livemode: false,
  created: 1609844336,
  id: 'pm_1I6DFcAgsVW5UJBhkPoBwOcz',
  type: 'card',
  card: {
  country: 'US', last4: '0341', funding: 'credit', checks: { address_postal_code_check: 'pass', address_line1_check: null, cvc_check: 'pass' }, three_d_secure_usage: { supported: true }, wallet: null, generated_from: null, fingerprint: 'pOLCnAkGISuK8bjb', exp_month: 1, exp_year: 2022, networks: { available: ['visa'], preferred: null }, brand: 'visa',
  },
  object: 'payment_method',
  customer: 'cus_IfG8JSTJM0o2mB',
  },
  },
  next_action: null,
  invoice: null,
  statement_descriptor_suffix: null,
  application_fee_amount: 182,
  object: 'payment_intent',
  customer: 'cus_IfG8JSTJM0o2mB',
  status: 'requires_payment_method',
  },
  message: 'Your card was declined.',
  type: 'card_error',
  payment_method: {
  billing_details: {
  name: null,
  address: {
  country: null, state: null, postal_code: '123123', city: null, line2: null, line1: null,
  },
  phone: null,
  email: null,
  },
  metadata: { test_key: 'test_value' },
  livemode: false,
  created: 1609844336,
  id: 'pm_1I6DFcAgsVW5UJBhkPoBwOcz',
  type: 'card',
  card: {
  country: 'US', last4: '0341', funding: 'credit', checks: { address_postal_code_check: 'pass', address_line1_check: null, cvc_check: 'pass' }, three_d_secure_usage: { supported: true }, wallet: null, generated_from: null, fingerprint: 'pOLCnAkGISuK8bjb', exp_month: 1, exp_year: 2022, networks: { available: ['visa'], preferred: null }, brand: 'visa',
  },
  object: 'payment_method',
  customer: 'cus_IfG8JSTJM0o2mB',
  },
  statusCode: 402,
  },
  payment_intent: {
  metadata: { reservation_id: '1610622661093-86' },
  livemode: false,
  canceled_at: null,
  amount_capturable: 0,
  description: null,
  source: null,
  statement_descriptor: null,
  transfer_data: { destination: 'acct_1I7YPZPJ2sxoFK8x' },
  shipping: null,
  review: null,
  currency: 'cad',
  id: 'pi_1IBtvEAgsVW5UJBhvbuugmlS',
  client_secret: 'pi_1IBtvEAgsVW5UJBhvbuugmlS_secret_xWLuPSJLphSETACG7k9Ul9a9x',
  payment_method_options: { card: { installments: null, request_three_d_secure: 'automatic', network: null } },
  payment_method: null,
  capture_method: 'automatic',
  amount: 1221,
  transfer_group: null,
  on_behalf_of: 'acct_1I7YPZPJ2sxoFK8x',
  created: 1611200004,
  payment_method_types: ['card'],
  amount_received: 0,
  setup_future_usage: null,
  confirmation_method: 'automatic',
  cancellation_reason: null,
  charges: {
  has_more: false,
  data: [{
  balance_transaction: null,
  billing_details: {
  name: null,
  address: {
  country: null, state: null, postal_code: '123123', city: null, line2: null, line1: null,
  },
  phone: null,
  email: null,
  },
  metadata: { reservation_id: '1610622661093-86' },
  livemode: false,
  destination: 'acct_1I7YPZPJ2sxoFK8x',
  description: null,
  failure_message: 'Your card was declined.',
  fraud_details: {},
  source: null,
  amount_refunded: 0,
  refunds: {
  has_more: false, data: [], total_count: 0, url: '/v1/charges/ch_1IBtvEAgsVW5UJBhhqHteeMr/refunds', object: 'list',
  },
  statement_descriptor: null,
  transfer_data: { destination: 'acct_1I7YPZPJ2sxoFK8x', amount: null },
  receipt_url: null,
  shipping: null,
  review: null,
  captured: false,
  calculated_statement_descriptor: 'VINEET PATIDAR',
  currency: 'cad',
  refunded: false,
  id: 'ch_1IBtvEAgsVW5UJBhhqHteeMr',
  outcome: {
  reason: 'generic_decline', risk_level: 'normal', seller_message: 'The bank did not return any further details with this decline.', network_status: 'declined_by_network', type: 'issuer_declined', risk_score: 27,
  },
  payment_method: 'pm_1I6DFcAgsVW5UJBhkPoBwOcz',
  order: null,
  dispute: null,
  amount: 1221,
  disputed: false,
  failure_code: 'card_declined',
  transfer_group: 'group_pi_1IBtvEAgsVW5UJBhvbuugmlS',
  on_behalf_of: 'acct_1I7YPZPJ2sxoFK8x',
  created: 1611200004,
  payment_method_details: {
   type: 'card',
  card: {
  country: 'US', last4: '0341', funding: 'credit', checks: { address_postal_code_check: 'pass', address_line1_check: null, cvc_check: null }, wallet: null, installments: null, fingerprint: 'pOLCnAkGISuK8bjb', exp_month: 1, exp_year: 2022, three_d_secure: null, brand: 'visa', network: 'visa',
  },
  },
  amount_captured: 0,
  source_transfer: null,
  receipt_number: null,
  application: null,
  receipt_email: null,
  paid: false,
  application_fee: null,
  payment_intent: 'pi_1IBtvEAgsVW5UJBhvbuugmlS',
  invoice: null,
  statement_descriptor_suffix: null,
  application_fee_amount: 182,
  object: 'charge',
  customer: 'cus_IfG8JSTJM0o2mB',
  status: 'failed',
  }],
  total_count: 1,
  url: '/v1/charges?payment_intent=pi_1IBtvEAgsVW5UJBhvbuugmlS',
  object: 'list',
  },
  application: null,
  receipt_email: null,
  last_payment_error: {
  doc_url: 'https://stripe.com/docs/error-codes/card-declined',
  charge: 'ch_1IBtvEAgsVW5UJBhhqHteeMr',
  code: 'card_declined',
  decline_code: 'generic_decline',
  message: 'Your card was declined.',
  type: 'card_error',
  payment_method: {
  billing_details: {
  name: null,
  address: {
  country: null, state: null, postal_code: '123123', city: null, line2: null, line1: null,
  },
  phone: null,
  email: null,
  },
  metadata: { test_key: 'test_value' },
  livemode: false,
  created: 1609844336,
  id: 'pm_1I6DFcAgsVW5UJBhkPoBwOcz',
  type: 'card',
  card: {
  country: 'US', last4: '0341', funding: 'credit', checks: { address_postal_code_check: 'pass', address_line1_check: null, cvc_check: 'pass' }, three_d_secure_usage: { supported: true }, wallet: null, generated_from: null, fingerprint: 'pOLCnAkGISuK8bjb', exp_month: 1, exp_year: 2022, networks: { available: ['visa'], preferred: null }, brand: 'visa',
  },
  object: 'payment_method',
  customer: 'cus_IfG8JSTJM0o2mB',
  },
  },
  next_action: null,
  invoice: null,
  statement_descriptor_suffix: null,
  application_fee_amount: 182,
  object: 'payment_intent',
  customer: 'cus_IfG8JSTJM0o2mB',
  status: 'requires_payment_method',
  },
  type: 'StripeCardError',
  payment_method: {
  billing_details: {
  name: null,
  address: {
  country: null, state: null, postal_code: '123123', city: null, line2: null, line1: null,
  },
  phone: null,
  email: null,
  },
  metadata: { test_key: 'test_value' },
  livemode: false,
  created: 1609844336,
  id: 'pm_1I6DFcAgsVW5UJBhkPoBwOcz',
  type: 'card',
  card: {
  country: 'US', last4: '0341', funding: 'credit', checks: { address_postal_code_check: 'pass', address_line1_check: null, cvc_check: 'pass' }, three_d_secure_usage: { supported: true }, wallet: null, generated_from: null, fingerprint: 'pOLCnAkGISuK8bjb', exp_month: 1, exp_year: 2022, networks: { available: ['visa'], preferred: null }, brand: 'visa',
  },
  object: 'payment_method',
  customer: 'cus_IfG8JSTJM0o2mB',
  },
  statusCode: 402,
  },
  payment_time: 1611200006,
  }],
  total_charges: 24.42,
  referee_booked: true,
  update_at: 1611200088,
  updated_by: { uid: 'aLaV61nfhEfmVgDKy5MAnDOtLHu1', first_name: 'kishan', last_name: 'makani' },
  total_game_charges: 22,
  reservation_id: '1610622661093-86',
  game_id: 'da7f9ff0-c5e5-40bc-a0b2-137eb1c97317',
  start_datetime: 1630434600,
  version: 5,
  initiated_by: 'aLaV61nfhEfmVgDKy5MAnDOtLHu1',
  created_at: 1610622661,
  hourly_game_fee: 22,
  stripe_fee: {
  refundable: 'non-refundable', fee_type: 'mixed', flat_fee: 0.3, fee: 2.9,
  },
  timestamp: 1611200088,
  source: 'pm_1I3vbwAgsVW5UJBhwcuIvzVv',
  sport: 'Tennis',
  activity_id: '4b259450-5b99-11eb-8080-80000e779b2f',
  referee_id: 'k9Ybsfd39hX3UAF1okasz2UqP3g1',
  referee_cancellation_policy: 'strict',
  requested_by: 'aLaV61nfhEfmVgDKy5MAnDOtLHu1',
  manual_fee: true,
  chief_referee: true,
  service_fee2_charges: 1.22,
  currency_type: 'CAD',
  total_payout: 20.78,
  end_datetime: 1630436400,
  service_fee1_charges: 2.42,
  payment_method_type: 'card',
  referee: {
  sports: ['Soccer', 'Tennis'],
  privacy_events: 'everyone',
  full_image: 'https://dev-townscup-gallery.s3.amazonaws.com/k9Ybsfd39hX3UAF1okasz2UqP3g1/366229b5-458e-4dbd-9474-4718cf06e4b6',
  full_name: 'Vineet Patidar',
  email: 'vineetpatidar@gmail.com',
  country: 'Canada',
  language: ['English', 'English(UK)', 'English(US)'],
  city: 'Vancouver',
  referee_data: [{
  sport_name: 'Tennis', certificates: [], is_published: true, fee: '22', cancellation_policy: 'strict', language: [{ language_name: 'English' }, { language_name: 'English(Canada)' }], descriptions: 'I am registering for tennis sport',
  }, {
  sport_name: 'Soccer',
  certificates: {
  nativeEvent: null, _dispatchInstances: null, eventPhase: null, _dispatchListeners: null, cancelable: null, defaultPrevented: null, bubbles: null, _targetInst: null, type: null, dispatchConfig: null, isTrusted: null, target: null,
  },
  is_published: true,
  fee: '17.80',
  cancellation_policy: 'strict',
  language: [{ language_name: 'English' }, { language_name: 'English(Singapore)' }],
  descriptions: 'Registering for soccer game',
  }],
  signedup_user: true,
  privacy_followers: 'everyone',
  thumbnail: 'https://dev-townscup-gallery.s3.amazonaws.com/k9Ybsfd39hX3UAF1okasz2UqP3g1/1f3ed9e3-b0df-492c-8b03-5972a4f6668f',
  location: 'Vancouver, BC, Canada',
  entity_type: 'player',
  privacy_profile: 'everyone',
  customer_id: 'cus_IfdQQlasYApQ06',
  state_abbr: 'BC',
  teamIds: ['62e38d12-0738-4431-beca-aa1763249988'],
  games: [{
  sport_name: 'Tennis', thumbnail: 'https://picsum.photos/id/320/100/100', full_image: 'https://picsum.photos/id/320/640/1136', totalGames: 0, sport_type: 'single-multiplayer', fee: '17.55',
  }],
  gender: 'Male',
  user_id: 'k9Ybsfd39hX3UAF1okasz2UqP3g1',
  last_name: 'Patidar',
  registered_sports: [{
  sport_name: 'Tennis', Tennis: 'single-multiplayer', fee: '17.55', language: ['English', 'English(UK)'], cancellation_policy: 'moderate', descriptions: 'I am registering for tennis', point: 500,
  }, {
  sport_name: 'Baseball', currency_type: 'CAD', fee: '10', language: ['English', 'English(Canada)', 'English(Singapore)'], cancellation_policy: 'strict', descriptions: 'Aaa', point: 500,
  }, {
  sport_name: 'Carom', currency_type: 'CAD', fee: '20', language: ['English', 'English(Canada)'], cancellation_policy: 'strict', descriptions: 'Dog', point: 500,
  }],
  first_name: 'Vineet',
  merchant_id: 'acct_1I7YPZPJ2sxoFK8x',
  birthday: 0,
  is_following: false,
  },
  },
  }],
  timestamp: 1611640102,
  venue: {
  address: 'Budapest, Deák Ferenc tér, Hungary', title: 'sds', venueType: 'other', lat: 47.4978371, long: 19.054419,
  },
  sport: 'Tennis',
  approval: { expiry: 1612089994, away_team: { reason: false, approved: true, by: { uid: 'aLaV61nfhEfmVgDKy5MAnDOtLHu1', first_name: 'kishan', last_name: 'makani' } } },
  challenge_scorekeepers: [{ is_chief: false, responsible_team_id: 'none' }],
  home_team_goal: 0,
  end_datetime: 1630436400,
  actual_startdatetime: 1611639970,
  }
