export default {
  townsCupTitle: 'en_TownsCup',
  alertmessagetitle: 'en_TownsCup',
  defaultError: 'en_Something went wrong',
  titleBasic: 'en_Townscup',
  townsCupTagLine: 'en_All sports in the world',
  welCome: 'en_Welcome',
  welcomeText: "en_You're only a few steps away from joining Townscup.",
  fbText: 'en_Continue with Facebook',
  googleText: 'en_Continue with Google',
  appleText: 'en_Continue with Apple',
  signUpText: 'en_Sign up with email',
  alreadyRegisteredMessage: 'en_Email address is already registered.',
  userNotFound: 'en_The email and password you entered do not match.',
  validEmailMessage: 'en_Please use a valid email address.',
  alreadyMember: 'en_Already a member?',
  notAMemberYetSignup: 'en_Not a member yet?',
  loginText: 'en_Log in',
  quitText: 'en_Quit',
  orText: 'en_OR',
  emailPlaceHolder: 'en_Email',
  allDay: 'en_All day',
  all: 'en_All',
  starts: 'en_Start',
  ends: 'en_End',
  until: 'en_Until',
  weekly: 'en_Weekly',
  addTime: 'en_Add time',
  setAvailable: 'en_Set available',
  block: 'en_Block',
  thisEvent: 'en_This event',
  assistRefereeTitle: 'en_Assistant Referee',
  thisAndFollowingEvent: 'en_This and all following events',
  recurringEventTitle: 'en_Update Recurring Event',
  selectTimePlaceholder: 'en_Select Repeat',
  selectInvoiceDuration: 'en_Select duration',
  addressPlaceholder: 'en_Address',
  positionPlaceholder: 'en_Position',
  birthDatePlaceholder: 'en_Birthday',
  AppearancePlaceholder: 'en_Appearance',
  injuredPlaceholder: 'en_Injured',
  longTermAwayPlaceholder: 'en_Long-term Away',
  suspendedPlaceholder: 'en_Suspended',
  writeNotesPlaceholder: 'en_Notes',
  writedownRulesPlaceholder: 'en_Write down the rules',
  enterEmailPlaceholder: 'en_Enter your email address',
  passwordPlaceHolder: 'en_Password',
  forgotPassword: 'en_Forgot Password?',
  checkEmailText: 'en_Please check your e-mail',
  checkEmailDescText:
    'en_We have sent you an email with a link to reset your password. It may take a few minutes for you to receive it.',
  signTerms:
    "en_By continuing you agree to Towny's Terms of Service, We will manage information about you as described in our PrivacyPolicy and Cookie Policy.",
  resetText: 'en_Reset your password.',
  nextTitle: 'en_NEXT',
  emailNotRegisterd: 'en_This email is not registered.',
  varificationLinkSend: 'en_Verification email was sent successfully.',
  deactivateTitle: 'en_DEACTIVATE ACTIVITY',
  deactivateAccountTitle: 'en_DEACTIVATE MY ACCOUNT',
  terminateAccount: 'en_TERMINATE ACCOUNT',
  pauseTeam: 'en_PAUSE TEAM',

  acceptTitle: 'en_ACCEPT',
  declineTitle: 'en_DECLINE',
  cancelRequestTitle: 'en_CANCEL REQUEST',
  confirmAndPayTitle: 'en_CONFIRM AND PAY',
  applyTitle: 'en_APPLY',
  cancelTitle: 'en_CANCEL',
  reservTitle: 'en_RESERVE',
  sendInviteTitle: 'en_SEND INVITE TO CHALLENGE',
  doneTitle: 'en_DONE',
  saveTitle: 'en_SAVE',
  moveTitle: 'en_MOVE',
  loginCapTitle: 'en_LOGIN',
  continueCapTitle: 'en_CONTINUE',
  signUpCapitalText: 'en_SIGN UP',
  fnameText: 'en_First Name',
  lnameText: 'en_Last Name',
  nameText: 'en_Name',
  save: 'en_Save',
  done: 'en_Done',
  apply: 'en_Apply',
  yes: 'en_Yes',
  no: 'en_No',
  passwordText: 'en_Password (at least 6 characters)',
  passwordWarningMessage: 'en_Password should be atleast 6 characters.',
  confirmPasswordText: 'en_Confirm Password',
  // Password message
  passwordCanNotBlank: 'en_Password cannot be blank.',
  cofirmpPswCanNotBlank: 'en_Confirm Password cannot be blank.',
  confirmAndPasswordNotMatch: 'en_Password and Confirm Password do not match.',
  appName: 'en_TownsCup',

  awaitingPayment: 'en_Awaiting Payment',
  pendingPayment: 'en_pendingpayment',
  requestSent: 'en_Request Sent',
  offered: 'en_offered',
  chiefReferee: 'en_CHIEF REFEREE',
  cancelled: 'en_canceled',
  Cancelled: 'en_Canceled',
  requestCancelled: 'en_requestcancelled',
  reqCan: 'en_Request Cancelled',
  accepted: 'en_accepted',
  Accept: 'en_Confirmed',
  declined: 'en_declined',
  Decline: 'en_Declined',

  amountTitle: 'en_Amount',
  noteTitle: 'en_Note',
  invoiceTitle: 'en_Invoice Title',
  amountDueTitle: 'en_Amount Due',
  invoiceDescTitle: 'en_Invoice Description (optional)',

  infoTitle: 'en_Info',
  recentMatchTitle: 'en_Recentest Match',
  aboutRatingTitle: 'en_Detail info about ratings',
  refereeRecentMatchTitle: 'en_Recentest Refereed Match',
  reviewsTitle: 'en_Reviews',
  upcomingMatchTitle: 'en_Upcoming Match',
  statsTitle: 'en_Stats',
  signedUpTime: 'en_Signed up in 2020',
  infoTeamTitle: 'en_Vancouver Teams FC',
  infoTeamCity: 'en_Vancouver, BC',
  ntrpTitle: 'en_NTRP',
  refereeFee: 'en_Referee Fee',
  cancellationPolicy: 'en_Cancellation Policies',
  gameFee: 'en_Match Fee',
  perHour: 'en_ (per hours)',
  ntrpSubTitle: 'en_ (The national tennis rating program)',
  homePlaceTitle: 'en_Home place',
  homePlaceValue: 'en_BC Place 2059 W 4th Ave, Vancouver, BC, V6J 1M7',
  clubTeamTitle1: 'en_New York City FC',
  clubTeamCity1: 'en_New york, NY',
  clubTeamTitle2: 'en_Chelsea FC',
  clubTeamTitle3: 'en_FC Barcelona',
  leagueTeamTitle: 'en_UEFA Champions League',

  locationText: 'en_Choose your city.',
  locationDescription:
    'en_Home city is the city where you currently reside or you mostly play sports.',
  locationPlaceholderText: 'en_Search by city or postal code',
  sportText: 'en_Select your favourite sports.',

  // Add Birthday screen
  addBirthdayText: 'en_Add your birthday.',
  notDisplayText: 'en_This won’t be displayed in your public profile.',
  whyAskingText: 'en_Why is TownsCup asking for my birthday?',
  birthDateChangeNote:
    'en_You can’t change your birthday once you have completed the sign-up process.',
  birthdatText:
    'en_You must be at least 13 years old to have a TownsCup account in most countries.\n\nIf account represents someone under the age of 13, the user must clearly state in the account’s bio that the account is managed by a parent or manager.\n\nThis information also helps TownsCup provide age-appropriate services to its users. Furthermore, this information is required when you join a group or sports game which has age requirements in the TownsCup Community.',

  // Choose gender screen
  addGenderText: 'en_Add your gender.',
  notDisplayGenderText: 'en_This won’t be displayed on your public profile.',
  whyAskingGenderText: 'en_Why is TownsCup asking for my gender?',
  genderText:
    'en_This information helps TownsCup provide gender-appropriate services to its users. Furthermore, this information is also required when you join a group or sports game which has gender-requirement in the TownsCup community.',
  maleRadioText: 'en_Male',
  femaleRadioText: 'en_Female',
  otherRadioText: 'en_Other',
  canNotChangeGender:
    'en_You can’t change your gender once you have completed the sign-up process.',
  // CreateTeam Screen 1
  star: 'en_*',
  newText: 'en_new',
  SportsTextFieldTitle: 'en_Choose a sport that the team will play.',

  SportsTextFieldClubTitle:
    'en_Choose sports that members or teams in the club will play.',
  selectSportPlaceholderPlayer: 'en_Which sport do you want to play?',

  selectSportPlaceholderReferee: 'en_Which sport do you want to referee?',
  selectSportPlaceholderScorekeeper:
    'en_Which sport do you want to scorekeeping?',

  teamNameTitle: 'en_What is the team name?',
  whichSport: 'en_SPORT',
  whichSportScorekeeper: 'en_Which sport do you want to scorekeeper?',

  whichLanguage: 'en_LANGUAGES',
  teamNamePlaceholder: 'en_Enter Team Name',

  enterNotePlaceholder: 'en_Enter notes',
  amountPlaceholder: 'en_Enter amount',

  playerTitle: 'en_Players',
  player1Title: 'en_Player 1',
  player2Title: 'en_Player 2',
  searchHereText: 'en_Search here',
  searchText: 'en_Search',
  genderTitle: "en_Choose player's gender.",
  curruencyType: 'en_Currency Type',
  feeCyclePlaceholder: 'en_Fees cycle',
  selectCode: 'en_Country Code',
  selectGenderPlaceholder: 'en_Select Gender',
  selectCurruencyTypePlaceholder: 'en_Select Currency Type',
  membersAgeTitle: "en_Range player's ages.",
  maxPlaceholder: 'en_Max',
  minPlaceholder: 'en_Min',
  locationTitle: 'en_Current City',

  locationClubTitle: 'en_Where is the home city of the club?',
  currentCity: 'en_Home City',
  birthdateText: 'en_Choose Date of birth',
  searchCityPlaceholder: 'en_Search by city or postal code',
  searchCityStatePlaceholder: 'en_City, state or country',
  searchByCityStateText: 'en_Search by city, state or country',
  cityText: 'en_City',
  stateText: 'en_State',
  countryText: 'en_Country',
  postalCodeText: 'en_Postal Code/Zip',
  requiredText: 'en_required',
  createClubNotes:
    'en_You can change the sports after you have created the club.',
  clubBelongText: 'en_The created team will belong to',
  clubText: 'en_Club',
  // CreateTeam Screen 2

  membershipTitle: 'en_Membership',
  whoJoinTitle: 'en_Who can join the team?',
  membershipRequestText:
    'en_A person whose membership request has been accepted by a team admin',
  inviteText: 'en_Invite only',
  canNotChangeServing: 'en_You can not change serving player during game.',
  // Create Team screen 3

  registerTitle: 'en_Registration Fee',
  registerSubTitle:
    'en_A team admin can send a new member the invoice for the registration fee after the member joins your team.',
  basicFeeTitle: 'en_Basic Fee',
  enterFeePlaceholder: 'en_Enter fee',
  venueNamePlaceholder: 'en_Venue Name',
  venueAddressPlaceholder: 'en_Address',
  venueDetailsPlaceholder: 'en_Details',
  feeDetailsText: 'en_Fee Details',
  feeDetailsPlaceholder: 'en_Write Details regarding the registration fee…',
  membershipFeeTitle: 'en_Membership Fee',
  membershipSubTitle:
    'en_A team admin can send a member the invoice for the membership fee regularly.',
  membershipPlaceholder: 'en_Write Details regarding the membership fee…',

  // CreateTeam Screen 4
  matchFeeTitle: 'en_Match fee',
  matchFeeSubTitle:
    'en_When your team accepts a game reservation request from another team and plays a game against the team, the team will pay your team the below amount of the match fee. It may be refunded when the game is canceled.',
  cancellationPolicyTitle: 'en_Cancellation Policies',
  cancellationpolicySubTitle:
    'en_Please, choose one the cancellation policies below',
  strictText: 'en_Strict',
  moderateText: 'en_Moderate',
  flexibleText: 'en_Flexible',
  requesterWarningText:
    'en_*Requester: The team or person who sends the game reservation request initialy *Requestee: The team or person who receives the game reservation request initialy',
  strictPoint1Title: 'en_Cancellation 14 days in advance',
  strictPoint2Title: 'en_Cancellation less than 14 days in advance',
  strictPoint3Title: 'en_Cancellation less than 24 hours in advance',
  strictPoint1Desc:
    'en_Free cancellation up to 14 days before the game reservation’s start time. However, the service fee is non-refundable.',
  strictPoint2Desc:
    'en_The challenger can cancel the game reservation up to 7 days before the game reservation’s start time and get a 50% refund of the match fee, excluding the service fee.',
  strictPoint3Desc:
    'en_If the challenger cancels less than 24 hours before the the game reservation’s start time,the match fee and service fee are non-refundable.',

  moderatePoint1Title: 'en_Cancellation 7 days in advance',
  moderatePoint2Title: 'en_Cancellation less than 7 days in advance',
  moderatePoint3Title: 'en_Cancellation less than 24 hours in advance',
  moderatePoint1Desc:
    'en_Free cancellation up to 7 days before the game reservation’s start time. However, the service fee is non-refundable.',
  moderatePoint2Desc:
    'en_The challenger can cancel the game reservation less than 7 days before the game reservation’s start time and get a 50% refund of the match fee, but not the service fee.',
  moderatePoint3Desc:
    'en_If the challenger cancels less than 24 hours before the game reservation’s start time, the match fee and service fee are non-refundable.',
  flexiblePoint1Title: 'en_Cancellation 24 hours in advance',
  flexiblePoint2Title: 'en_Cancellation less than 24 hours in advance',
  flexiblePoint1Desc:
    'en_Free cancellation up to 24 hours before the game reservation’s start time. However, the service fee is non-refundable.',
  flexiblePoint2Desc:
    'en_If the challenger cancels less than 24 hours before the game reservation’s start time, the match fee and service fee are non-refundable.',

  // CreateClub Screen 1
  clubNameTitle: 'en_What is the club name?',
  clubNameplaceholder: 'en_Club name',

  // CreateClub Screen 2
  inviteTitle: 'en_Invitation to Membership',
  userText: 'en_USER',
  userSubtitle: 'en_Does a user need an invitation from the club to join It?',
  noUserText: 'en_No, a user doesn’t.',
  yesUserText: 'en_Yes, a user does.',
  teamText: 'en_TEAM',
  teamSubTitle: 'en_Does a user need an invitation from the club to join It?',
  noTeamText: 'en_No, a team doesn’t.',
  yesTeamText: 'en_Yes, a team does.',
  approvalTitle: 'en_Approval for Membership request',
  approveTitle: 'en_APPROVE',
  approvalUserSubTitle:
    'en_Does a user need the approval for his or her membership request from the club to join it?',
  approvalTeamSubTitle:
    'en_Does a user need the approval for its membership request from the club to join it?',
  whoJoinText: 'en_Who can join the club?',
  everyoneText: 'en_Everyone and Every team',
  onlyPersonText: 'en_Only person or team invited by club',
  whoseApprovalText:
    'en_Whose approval does an applicant need when joining the club?',
  noneText: 'en_None',
  clubAdminText: 'en_A club admin',
  inviteUserText: 'en_Invite user to club',
  goToClubText: 'en_Go to club home',
  // Register Player Screen
  sportsEventsTitle: 'en_Sport',
  descriptionText: 'en_Description',
  describeSelf: 'en_DESCRIPTION ABOUT YOUR SELF',
  opetionalText: 'en_(Optional)',
  descriptionPlaceholder: 'en_Describe yourself as a personal player',
  matchFeesTitle: 'en_Match Fee',
  perHourText: 'en_(per hour)',
  perGameText: 'en_(per game)',
  configureEmailText:
    'en_Can not open mail composer, please setup mail account from seting',

  // Register Referee Screen
  certificateTitle: 'en_Certificates',
  certiTitle: 'en_CERTIFICATE',
  addCertiTitle: 'en_Add a Certificate',
  addCertiMainTitle:
    'en_Please add the certificates or documents showing your professional experience.',
  descriptionRefereePlaceholder: 'en_Describe yourself as a referee',
  certificateSubTitle:
    'en_Please add the certificates or documents showing your professional experience.',
  addCertificateTitle: 'en_ + Add Image of Certificate',
  languageTitle: 'en_Language',
  languagePlaceholder: 'en_What languages can you speak?',
  refereeFeesTitle: 'en_Referee Fee',
  deleteTitle: 'en_Delete',
  profilePhotoUser: 'en_Profile Photo Of User Account',
  titleOrDescriptionText: 'en_Add title of certificate',
  title: 'en_TITLE',
  sportCreateEvent: 'en_SPORT',
  numberOfAttend: 'en_NUMBER OF ATTENDEES',
  eventFeeTitle: 'en_EVENT FEE',
  refundPolicyTitle: 'en_REFUND POLICY',
  whereEventPosted: 'en_WHERE THE EVENT IS POSTED',
  sportPlaceholder: 'en_Choose sport',
  titlePlaceholder: 'en_Title',
  createTitleValue: 'en_Welcome Season Party',
  titleValue: 'en_Games with Vancouver Whitecaps',
  about: 'en_About',
  description: 'en_DESCRIPTION',
  aboutPlaceholder: 'en_Describe about event.',
  createAboutValue:
    'en_I love playing soccer, Association football, commonly known as football or soccer, [a] is a sport played between seven teams of eleven with a spherical ball.',
  aboutValue:
    'en_I love playing soccer, Association football, more commonly known as football or soccer, [a] is a team sport played between seven teams of eleven players with a spherical ball.',
  eventColorTitle: 'en_Event Color',
  eventCreatedTitle: 'en_Events Created By You',
  groupEventTitle:
    'en_The events of which group do you want to be displayed in your schedule?',
  eventImportedTitle: 'en_Event Imported From Other Groups',
  games: 'en_Games',
  scheduleMatchTitle: 'en_Scheduled Matches',
  timeTitle: 'en_DATE & TIME',
  from: 'en_From',
  fromTime: 'en_Feb 15, 2019 1:00 am',
  date: 'en_Jan 25, 2019',
  time: 'en_12:00 am',
  to: 'en_To',
  repeat: 'en_Repeat',
  repeatTime: 'en_Weekly \n(Until Mar 25, 2019 12:00 am)',
  place: 'en_VENUE',
  placeName: 'en_800 Griffiths Way, Vancouver, BC V6B 6G1',
  availableTitle: 'en_Challenge Availability',
  scheduleTitle: 'en_Schedule',
  whoCanSeeShcedule: 'en_Who can see your schedule?',
  availableSubTitle:
    'en_Do you want to be available for challenges during this event?',
  available: 'en_Available For Challenge',
  blocked: 'en_Blocked For Challenge',
  editChallengeTitle:
    'en_Set the time to be available to receive a challenge request or block it.',

  // Group setting & Privacy
  connectionTitle: 'en_Connetions',
  whoCanSeeClub: 'en_Who can see members in club connections?',
  whoCanSeeTeam: 'en_Who can see members in team connections?',
  whoCanSeeClubFollowers: 'en_Who can see followers in club connections?',
  whoCanSeeTeamFollowers: 'en_Who can see followers in team connections?',
  everyoneRadio: 'en_Everyone',
  everyTeam: 'en_Every team',
  acceptedByClub: 'en_A team whose request has been accepted by club',
  personWhoRequest:
    'en_A person whose request has been accepted by team admins',
  inviteOnly: 'en_Invite only',
  followersRadio: 'en_Followers',
  clubMembersRadio: 'en_Club Members',
  adminsRadio: 'en_Only Club & Team Admins',

  // Change password
  oldPassword: 'en_Current Password',
  newPassword: 'en_New Password',
  confirmPassword: 'en_Confirm Password',
  atLeastText: 'en_(At least 6 characters)',

  // reservation

  doneByText: 'en_Done by',
  detailText: 'en_DETAILS',
  respondWithinText: 'en_RESPOND',
  noReservationFountText: 'en_No Reservations Found',
  // member connection
  connectAccountText: 'en_Invite or Connect Account',
  connectProfile: 'en_Connect the profile to this account',
  sendInvite: 'en_Send invitation to this e-mail account',
  connectMemberProfile: 'en_Connect this member to profile',
  createOtherProfile: 'en_Create another member profile',
  goToMemberProfile: 'en_GO TO MEMBERS',
  enterFirstNamePlaceholder: 'en_Enter First Name',
  firstName: 'en_First Name',
  lastName: 'en_Last Name',
  enterLastNamePlaceholder: 'en_Enter Last Name',
  enterBioPlaceholder: 'en_Enter Your Biography',
  enterAboutPlaceholder: 'en_Enter Your About',

  inviteEmailText:
    'en_Please enter the e-mail account of the person that you want to invite.',
  inviteSearchText: 'en_Who do you want to invite to your team?',
  inviteEventText: 'en_Who do you want to invite to the event?',

  admin: 'en_Admin',
  addEmailText: 'en_+ Add E-Mail',
  addPhone: 'en_+ Add Phone',
  addPosition: 'en_+ Add Position',
  camera: 'en_Camera',
  album: 'en_Album',
  editprofiletitle: 'en_Edit Profile',
  slogan: 'en_Slogan',
  lookingForTeam: 'en_Looking for a team?',
  hiringPlayers: 'en_Hiring players?',
  enterSloganPlaceholder: 'en_Enter Your Slogan',
  invitationSent: 'en_Invitation sent',
  userNotFoundByEmail: 'en_We didn’t find a user whose e-mail account is',
  jerseyNumberPlaceholder: 'en_Jersey Number',

  abouttitle: 'en_About',
  basicinfotitle: 'en_Basic Info',
  membershipFeesTitle: 'en_Membership Fees',
  teamstitle: 'en_Teams',
  clubstitle: 'en_Clubs',
  leaguesTitle: 'en_League',
  signedupin: 'en_Signed up in ',
  editabouttitle: 'en_Edit About',
  editbasicinfotitle: 'en_Edit Basic Info',
  birth: 'en_Birth',
  yearOfBirth: 'en_Year of Birth',
  gender: 'en_Gender',
  phone: 'en_Phone',
  mostUsedFoot: 'en_Most Used Foot',
  currrentCityTitle: 'en_Current City',
  height: 'en_Height',
  weight: 'en_Weight',
  heightTypeText: 'en_Height type',
  weightTypeText: 'en_Weight type',
  cm: 'en_cm',
  ft: 'en_ft',
  kg: 'en_kg',
  pound: 'en_pound',
  heightplaceholder: 'en_Enter Your Height',
  weightplaceholder: 'en_Enter Your Weight',
  playin: 'en_Plays In',
  refereesin: 'en_Referees In',
  scorekeeperIn: 'en_Scorekeeper In',
  totalGames: 'en_game',
  message: 'en_Message',
  followSportTeam: 'en_Follow sport Groups.',
  follow: 'en_Follow',
  following: 'en_Following',
  invite: 'en_Invite',
  member: 'en_Member',
  join: 'en_Join',
  joining: 'en_Joining',
  challenge: 'en_Challenge',

  // Message
  noMessageFountText: 'en_No Message Found',

  other: 'en_other',
  others: 'en_others',
  and: 'en_and',

  pendingrequests: 'en_PENDING REQUESTS',
  today: 'en_TODAY',
  earlier: 'en_EARLIER',

  trashmessage:
    'en_Notifications in trash will be permanently deleted 60 days after they are moved in trash.',
  left: 'en_left',
  responsetime: 'en_* Response time :',
  responsetimeexpired: 'en_RESPONSE PERIOD EXPIRED',
  decline: 'en_DECLINE',
  accept: 'en_ACCEPT',
  respond: 'en_RESPOND',
  calcelRequest: 'en_CANCEL REQUEST',
  cancelAlterRequest: 'en_CANCEL ALTERATION REQUEST',
  cancelMatch: 'en_CANCEL GAME',
  cancelreservation: 'en_CANCEL RESERVATION',
  alterReservation: 'en_CHANGE RESERVATION',
  sendAlterRequest: 'en_SEND ALTERATION REQUEST',
  cancel: 'en_Cancel',
  goToGameHome: 'en_GO TO GAME HOME',
  alreadyjoinclubmessage:
    'en_Your team can’t join this club because a team can join only a club.',
  isinvitedsuccesfully: 'en_is invited successfully',

  bioPrivacyTitle: 'en_Who can see Bio?',
  basicInfoPrivacyTitle: 'en_Who can see each category in Basic Info?',
  ntrpPrivacyTitle: 'en_Who can see NTRP?',
  homePlacePrivacyTitle: 'en_Who can see Home Place?',
  teamPrivacyTitle: 'en_Who can see Teams?',
  clubPrivacyTitle: 'en_Who can see Clubs?',
  leaguePrivacyTitle: 'en_Who can see Leagues?',
  certiPrivacyTitle: 'en_Who can see Certificates?',
  refereeFeePrivacyTitle: 'en_Who can see Referee Fee?',

  bio: 'en_Bio',
  contact: 'en_Contact',
  website: 'en_Website',
  emailtitle: 'en_Email',
  office: 'en_Office',
  homefield: 'en_Home Field',
  NA: 'en_n/a',
  addwebsite: 'en_Add Website',
  addemail: 'en_Add Email',
  addphone: 'en_Add Phone',
  addoffice: 'en_Add Office',
  addhomefield: 'en_Add Home Field',
  editcontact: 'en_Edit Contact',
  editbio: 'en_Edit Bio',
  enterwebsite: 'en_Enter Website',
  enteremail: 'en_Enter Email',
  enterphonenumber: 'en_Enter Phone Number',
  officeaddress: 'en_Office Address',
  homeaddress: 'en_Home Address',
  membersTitle: 'en_Members',
  noMembersText: 'en_No members',
  noMebersFoundText: 'en_No Members Found',
  sport: 'en_Sport',
  hometown: 'en_Home town',
  membersgender: "en_Member's gender",
  membersage: "en_Member's age",
  language: 'en_Language',
  languagesName: 'en_Korean, English, Hindi, Italian',
  membershipregfee: 'en_Membership registration fee',
  officeAddress: 'en_Office Address',
  membershipfee: 'en_Membership Fee',
  CADpermatch: 'en_CAD / MATCH',
  addaddress: 'en_Add Address',
  addbirth: 'en_Add Birthday',
  addgender: 'en_Add Gender',
  addheight: 'en_Add Height',
  addweight: 'en_Add Weight',
  gamefeetitle: 'en_Match Fee',
  perhoursinbracket: 'en_(per hours)',
  gamefeeperhour: 'en_Match Fee Per Hour',
  CAD: 'en_CAD',
  defaultCurrency: 'en_USD',
  currencyplacholder: 'en_Select Currency',
  languages: 'en_Languages',
  sportcannotbeblank: 'en_Sports cannot be blank',
  week: 'en_week',
  biweek: 'en_biweek',
  month: 'en_month',
  year: 'en_year',
  bylaw: 'en_Bylaw',
  editbylaw: 'en_Edit Bylaw',
  enterBylawPlaceholder: 'en_Enter Bylaw',
  leagues: 'en_Leagues',
  tcpoint: 'en_TC Points',
  matchAmountTitle: 'en_Match Fee',
  tcranking: 'en_TC Ranking',
  history: 'en_History',
  addrole: 'en_Add',
  addPlaying: 'en_Add playing',
  addRefereeing: 'en_Add refereeing',
  refereeOffer: 'en_Send referee offer',
  scorekeeperOffer: 'en_Send scorekeeper offer',
  addScorekeeping: 'en_Add scorekeeping',
  cards: 'en_Cards',
  addcard: 'en_Add New Card...',
  endingin: 'en_ ****',
  addacard: 'en_Add a Card',
  entergamefee: 'en_Enter Match Fee',
  matchfee: 'en_Match fee',
  refereeFeecardText: 'en_Referee fee',
  scorekeeperFee: 'en_Scorekeeper fee',
  firstnamevalidation: 'en_First name cannot be blank',
  lastnamevalidation: 'en_Last name cannot be blank',
  locationvalidation: 'en_Location cannot be blank',
  validEmailValidation: 'en_Please enter valid email address.',
  heightValidation: 'en_Please select height measurement',
  validHeightValidation: 'en_Please enter valid height.',
  weightValidation: 'en_Please select weight measurement',
  validWeightValidation: 'en_Please enter valid weight.',

  addOptionMessage: 'en_+ Add a payment method',
  addPayoutMessage: 'en_+ Add a payout method',

  selectPaymentText: 'en_Please select payment method.',
  selectPaymentMethod: 'en_Select a payment method',
  selectPayoutMethod: 'en_Select a payout method',
  cannotAcceptText:
    'en_Reservation can not be change after game has been started.',
  refereeOfferExpiryText: 'en_Offer expired or game start time already passed.',
  scorekeeperOfferExpiryText:
    'en_Offer expired or game start time already passed.',

  selectCardText: 'en_Please select payment method.',
  reservationRequestSent: 'en_SENT',
  reservationRequestPending: 'en_PENDING',
  reservationConfirmed: 'en_CONFIRMED',
  reservationDeclined: 'en_DECLINED',
  alterationRequestSent: 'en_ALTERATION REQUEST SENT',
  alterationRequestPending: 'en_ALTERATION REQUEST PENDING',
  reservationCancelled: 'en_CANCELLED',
  reservationRestored: 'en_RESTORED',
  reservationAwaitingPayment: 'en_AWAITING PAYMENT',
  alterationRequestCancelled: 'en_ALTERATION REQUEST CANCELLED',
  challenger: 'en_Challenger',
  challengee: 'en_Challengee',
  requester: 'en_Requester',
  requestee: 'en_Requestee',

  // reservation request

  reservationRequestAccepted: 'en_Reservation request accepted',
  reservationRequestDeclined: 'en_Reservation request declined',
  reservationRequestCancelled: 'en_Reservation request cancelled',
  reservationRequestRestored: 'en_Reservation request restored',
  reservationRequestApproved: 'en_Reservation request approved',

  reservationAlterRequestAccepted: 'en_Alteration request accepted',
  reservationAlterRequestDeclined: 'en_Alteration request declined',
  reservationAlterRequestCancelled: 'en_Alteration request cancelled',

  gameHomeText: 'en_GAME HOME',
  restorePreviousText: 'en_RESTORE TO PREVIOUS VERSION',
  tryToPayText: 'en_TRY TO PAY AGAIN',

  sportAlreadyRegisterd: 'en_This sport already registerd.',
  choosePayment: 'en_Please choose payment method.',
  chooseFutureDate: 'en_Please choose future date for challenge.',
  chooseCorrectDate: 'en_Please choose correct date and time.',
  max5Referee: 'en_Maximum 5 referees can be added.',
  maxVenue: 'en_Maximum 10 venue can be added.',
  maxPeriod: 'en_Maximum 10 period can be added.',
  maxOverTime: 'en_Maximum 10 overtime can be added.',

  max5Scorekeeper: 'en_Maximum 5 scorekeeper can be added.',
  serchByLocation: 'en_Search by address',
  cannotChangeReservationText:
    'en_Reservation can not be change after game has been started.',
  cannotChangeReservationGameStartedText:
    'en_Reservation can not be change after game time has beed expired or offer expired.',
  cannotCancelReservationText:
    'en_Reservation cannot be cancel after game time passed or offer expired.',
  selectSetText: 'en_Select sets',
  selectNumberOfGameText: 'en_Select number of games',
  gameScoreText: 'en_Select game score',
  selectWiningPoints: 'en_Select wining points',
  selectPointsText: 'en_Select points',
  selectAnyCard: 'en_Please choose any of the card.',
  selectAnyPayoutmethod: 'en_Please choose any of the payout method.',

  networkConnectivityErrorMessage:
    'en_Could not connect to the internet. Please check your network',
  recentPointDelete: 'en_The recentest won point will be canceled.',
  noWonPoint: 'en_Score not added yet.',
  gameNotStarted: 'en_Game not started yet.',
  gamePaused: 'en_Game is paused.',
  gameEnded: 'en_Game is ended.',
  selectTeam: 'en_Please Select Team',
  deactiveConfirmationText:
    'en_Are you sure you want to deactivate Tennis singles?',
  resetMatchRecord: 'en_Do you want to reset all the match records?',
  reviewForTeams: 'en_Review for Teams',
  reviewForPlayers: 'en_Review for Players',
  reviewForReferees: 'en_Review for Referees',
  editReviewForTeams: 'en_Edit Review for Teams',
  completeReviewFirst:
    'en_Please, complete all ratings before moving to the next.',
  punchualityDesc: 'en_Did the the referee arrive at the match place on time?',
  punchualityDescScorekeeper:
    'en_Did the the scorekeeper arrive at the match place on time?',
  chooseTeamFirst: 'en_Please choose any one team for review.',
  descriptionScorekeeperPlaceholder: 'en_Describe yourself as a scorekeeper',

  editReviewText: 'en_EDIT REVIEW FOR A TEAM',
  leaveReviewText: 'en_LEAVE REVIEW FOR A TEAM',
  leaveOrEditReviewText: 'en_LEAVE OR EDIT YOUR REVIEW',

  editReviewPlayerText: 'en_EDIT REVIEW FOR A PLAYER',
  leaveReviewplayerText: 'en_LEAVE REVIEW FOR A PLAYER',
  leaveOrEditReviewPlayerText: 'en_LEAVE OR EDIT YOUR REVIEW',

  bookReferee: 'en_BOOK REFEREE',
  bookScorekeeper: 'en_BOOK SCOREKEEPER',
  refereeRequestScreenTitle: 'en_Referee Reservation Request',
  refereeScreenTitle: 'en_Referee Reservation',

  scorekeeperRequestScreenTitle: 'en_Scorekeeper Reservation Request',
  scorekeeperScreenTitle: 'en_Scorekeeper Reservation',
  chooseScorekeeperText: 'en_Choose a scorekeeper',

  privacySettings: 'en_Privacy Settings',
  gameEndedAlertText: 'en_Game is ended, so you can not change reservation.',
  enterValidGameFee: 'en_Please enter valid match fee.',
  whatsGoingText: "en_What's going on?",
  writeText: 'en_Please write some text or select any image.',
  cannotCancelReservationAfterGameStartText:
    'en_Reservation cannot be cancel after game game has beed started.',
  cannotChooseDatetime:
    'en_This datetime is overlapping with blocked datetime.',
  recentMatchesTitle: 'en_Recent Matches',
  upcomingMatchesTitle: 'en_Upcoming Matches',
  lookingForTitle: 'en_Available for Challenge',
  shortsTitle: 'en_Shorts',
  hiringPlayerTitle: 'en_Recruiting Members',
  lookingForTeamTitle: 'en_Looking For Team/Club',
  refereesTitle: 'en_Referees',
  chooseSetting: 'en_Choose Setting',
  scorekeeperTitle: 'en_Scorekeepers',
  searchTitle: 'en_Search by city, state or country',
  challengeeSecureText: 'en_The challengee secures the match place',
  challengerSecureText: 'en_The challenger secures the match place',
  recentMatchPlaceholderText: 'en_NO RECENT MATCHES',
  upcomingMatchPlaceholderText: 'en_NO UPCOMING MATCHES',
  challengerPlaceholderText:
    'en_There is no challenge.\nWould you like to start your challenge?',
  hiringPlayersPlaceholderText: 'en_NO GROUPS',
  lookingTeamsPlaceholderText: 'en_NO PLAYERS',
  refereesPlaceholderText: 'en_NO REFEREES',
  scorekeepersPlaceholderText: 'en_NO SCOREKEEPERS',
  taggedPeopleText: 'en_Tagged People',
  taggedMatchesText: 'en_Tagged matches',

  manageChallengeText: 'en_MANAGE CHALLENGE',
  manageChallengeDetailText:
    'en_In order to receive challenges,\nyou must complete Manage Challenge.',

  sportsText: 'en_Choose a sport that the you want to play.',
  languageText: 'en_Which languages can you communicate in.',
  descriptionTextDetails: 'en_Describe yourself in the sport.',
  descriptionTeamTextDetails:
    'en_Describe the team more so that people can know about the team.',
  descriptionTeamTextPlaceholder: 'en_Describe the team.',

  descriptionClubTextDetails:
    'en_Describe the club more so that people can know about the club.',
  descriptionClubTextPlaceholder: 'en_Describe the club.',

  noFollowersTocreateTeam:
    'en_You have no followers, so you can not create team.',
  followersDescription:
    'en_Who do you want to make the team with? Choose a person among your followers.',
  followersPlaceholder: 'en_Search',
  photoUploadTitle:
    'en_Review the team, and add the profile photo and cover photo.',

  invitetocreateteam: 'en_Invite to create team',

  whouldYouLikeToAccept:
    'en_Would you like to accept this invite create a team?',
  photoUploadClubTitle:
    'en_Review the club, and add the profile photo and cover photo.',

  playersGenderText: "en_Player's Gender",

  manageChallengeShhetItem: 'en_Manage Challenge',
  challengeSettingTitle:
    'en_These challenge settings will be applied when a team challenges your team. When your team challenges another team, the team’s challenge setting will be applied for the challenge.',

  challengeSettingNotes:
    'en_In order to activate the “challenge” button and receive a challenge (game Reservation request), please fill in and save all the lists below.',

  refereeSettingHeading:
    'en_These referee reservation settings will be applied when you receive a referee reservation request.',
  refereeSettingNotes:
    'en_In order to activate the "book referee" button and receive a referee reservation request, please fill in and save all the lists above.',
  gameTyleTitle: 'en_Choose a game type.',
  officialTypeText:
    'en_The game result has an effect on TC points and TC level of the challenger and you.',
  friendlyTypeText:
    'en_The game result has no effect on TC points and TC level of the challenger and you.',

  scorekeeperSettingHeading:
    'en_These scorekeeper reservation settings will be applied when you receive a scorekeeper reservation request.',
  scorekeeperSettingNotes:
    'en_In order to activate the "book scorekeeper" button and receive a scorekeeper reservation request, please fill in and save all the lists above.',

  officialGameType: 'en_Official',
  friendlyGameType: 'en_Friendly',

  refuncPolicyTitle: 'en_Choose one of refund policies',

  gameFeeTitle:
    'en_Set the match fee that you want to receive from the challenger.',
  gameFeeTitleTeam:
    'en_Set the match fee that your team wants to receive from the challenger.',

  refereeFeeTitle: 'en_Set the referee fee that you want to charge per hour.',
  scorekeeperFeeTitle:
    'en_Set the scorekeeper fee that you want to charge per hour.',

  gameRulesTitle:
    'en_Write down the rules of the game you will play against the challenger.',

  gameRulesSubTitle1: 'en_General rules',
  gameRulesSubTitle2: 'en_Special rules',

  generalRulesPlaceholder:
    'en_Add the rules that are generally used in this sport.',
  specialRulesPlaceholder:
    'en_Add any rules that are unique or that you want to emphasize.',

  venueTitle:
    'en_Add at lease one venue that you will be able to secure for a game against a challenger at your expense.',

  homeAwayTitle:
    'en_Choose which team will be the home team and the away team.',
  availibilityTitle: 'en_Are you ready to accept new challenges?',
  availibilityRefereeTitle:
    'en_Are you ready to receive new referee Reservation requests?',
  availibilityScorekeeperTitle:
    'en_Are you ready to receive new scorekeeper Reservation requests?',

  AvailibilitySubTitle: 'en_Accept new challenges',

  AvailibilityRefereeSubTitle: 'en_Yes, I am ready.',

  officialOnly: 'en_Official only',
  friendlyOnly: 'en_Friendly only',
  allType: 'en_All',

  refereeSettingTitle:
    'en_How many referees will your team hire for a game at its own cost?',
  refereeSettingNote:
    'en_Which team will secure the referee at its own expense?',

  refereeRules1:
    'en_• Your team must secure the follwing number of referees for a game at its own cost within 5 days after the challenge is accepted.',
  refereeRules2:
    'en_• If your team isn’t reserving the following number of referees 5 days after the challenge is accepted, the confirmed game may be canceled.',
  scorekeeperSettingTitle:
    'en_How many scorekeepers will your team hire for a game at its own cost?',
  scorekeeperSettingNote:
    'en_Which team will secure the scorekeeper at its own expense?',

  scorekeeperRules1:
    'en_• Your team must secure the follwing number of scorekeepers for a game at its own cost within 5 days after the challenge is accepted.',
  scorekeeperRules2:
    'en_• If your team isn’t reserving the following number of scorekeepers 5 days after the challenge is accepted, the confirmed game may be canceled.',
  gameDurationTitle1: 'en_Set the Game duration.',
  gameDurationTitle2:
    'en_If the scores are tied at the end of the periods above,',
  detailsTitleText: 'en_Please add more details if needed.',

  firstPeriodText: 'en_1st Period',
  intervalText: 'en_Interval',
  secondPeriodText: 'en_2nd Period',

  withoutOverTimeText: 'en_the game ends without over time.',
  withOverTimeText: 'en_the game goes into over time.',

  addAreaText: 'en_Add areas where you can referee a game.',
  setRangeText: 'en_Set the range where you can referee a game',

  addAreaScorekeeperText: 'en_Add areas where you can scorekeeper a game.',
  setRangeScorekeeperText: 'en_Set the range where you can scorekeeper a game',

  firstOverTimeText: 'en_1st overtime',
  minuteText: 'en_min.',
  totalTimeTitle: 'en_Total time :',

  inviteToChallengeText:
    'en_Through “Invite to challenge”, you can invite another team to challenge your team.',

  teamExist: 'en_The team name in the sports already exists in the city.',
  sportActivity: 'en_Sports Activities',
  refereeRegisteredSuccess: 'en_Registered as a referee.',
  scorekeeperRegisteredSuccess: 'en_Registered as a scorekeeper.',
  terminationAlert: "en_The email and password you entered don't match.",
  organizerTitle: 'en_ORGANIZER',
  eventHost: 'en_EVENT HOST',
  goingTitle: 'en_GOING',

  whoCanJoin: 'en_WHO CAN JOIN',
  whoCanSee: 'en_WHO CAN SEE',

  // Signup & login text
  next: 'en_Next',
  signUp: 'en_Sign Up',
  addYourName: 'en_Add your name.',
  signupwithemail: 'en_Sign up with email',
  // Profile
  pleaseaddfirstname: 'en_Please add first name.',
  pleaseaddlastname: 'en_Please add last name.',
  searchByCity: 'en_Search by city',
  teamName: 'en_Team Name',
  clubName: 'en_Club Name',
  pleaseAddClubName: 'en_Please add club name.',
  pleaseAddTeamName: 'en_Please add team name',
  // Basic Info
  streetAddress: 'en_Street Address',
  postalCode: 'en_Postal Code',
  // Members
  isYourTeamRecruitingMember: 'en_Is your team recruiting a new member?',
  whoCanJoinTeam: 'en_Who can join the team?',
  configureYourRefereeSetting:
    'en_You can’t send offer, please configure your referee setting first.',
  emailPasswordWrong: 'en_The email and password you entered dont match.',
  passwordWrong: 'en_Your password is wrong.',
  // Referee & Scorekeeper
  hirer: 'en_hirer',
  referee: 'en_referee',
  match: 'en_Match',
  chooseagame: 'en_Choose a game',
  dateAndTime: 'en_date & time',
  start: 'en_start',
  end: 'en_end',
  venue: 'en_Venue',
  address: 'en_Address',
  matchrules: 'en_Match rules',
  chieforassistant: 'en_Chief or Assistant',
  refundpolicy: 'en_Refund Policy',
  payment: 'en_Payment',
  earning: 'en_Earning',
  servicefee: 'en_Service fee',
  totalamount: 'en_Total amount',
  totalearning: 'en_Total earning',
  timezone: 'en_Time zone',
  paymentMethod: 'en_Payment Method',
  internationalCardFee: 'en_International card fee',
  refereebookingnote:
    'en_By selecting the button below, I agree to the Game Rules cancellation policy and refund policy. I also agree to pay the total amount shown above.',
  scorekeeper: 'en_Scorekeeper',

  // Challenge screen
  typeOfGame: 'en_Match Type',
  matchFee: 'en_Match Fee',
  homeAndAway: 'en_Home & Away',
  gameDuration: 'en_Game Duration',
  refundPolicy: 'en_Cancellation Policy',
  matchDuration: 'en_Match Duration',
  venueName: 'en_Venue name',
  everyEvent: 'en_Every event',
  eventCreatedByUser: 'en_Event created by personal user',
  eventCreatedByGroup: 'en_Event create by group',
  none: 'en_None',
  switchAccount: 'en_Switch Account',
  moreText: 'en_more',
  noShortsText: 'en_NO SHORTS',
  postShortsText: 'en_Post your short >',
  noPlayerTeamText: 'en_NO AVAILABLE TEAMS OR PLAYERS',
  noPostFoundText: 'en_No Post Found',
  feedTitleText: 'en_Feed',
  everyoneTitleText: 'en_Everyone',
  onlymeTitleText: 'en_Only me',
  followerTitleText: 'en_Followers',
  memberInGroupText: 'en_Members in my groups',
  writeTextOrImage: 'en_Please write some text or select any image.',
  privacySettingText: 'en_Privacy Setting',
  feeTitleText: 'en_Fee',
  enterHeightText: 'en_Enter Height',
  enterWeightText: 'en_Enter Weight',
  rightWord: 'en_Right',
  leftWord: 'en_Left',
  poseWord: 'en_Pose',
  selectMostUsedFootText: 'en_Select Most Used Foot',
  dollerSign: '$',

  editBioText: 'en_Edit Bio',
  editBasicInfoText: 'en_Edit Basic Info',
  editFeeText: 'en_Edit Fee',
  editNTRPText: 'en_Edit NTRP',
  editHomePlaceText: 'en_Edit Home Place',
  editCertificateText: 'en_Edit Certificates',
  editPolicyText: 'en_Edit Policy',

  englishLangText: 'en_English',
  englishCanadaLangText: 'en_English(Canada)',
  englishSingaporeLangText: 'en_English(Singapore)',
  englishUKLangText: 'en_English(UK)',
  englishUSLangText: 'en_English(US)',
  deutschLangText: 'en_Deutsch',
  italianoLangText: 'en_Italiano',
  koreanLangText: 'en_Korean',
  cadPerHourText: 'en_CAD/hours',
  availableAreaText: 'en_Available Area',
  noAreaFoundText: 'en_No Area found',
  noSettingConfigureText: 'en_No Setting Configured Yet',
  editTitleText: 'en_Edit',
  policyTitleText: 'en_Policy',
  titleAndPhotosText: 'en_Title and photos',
  certificateNameText: 'en_Please Enter Certificate Name!',
  selectCertificateImageText: 'en_Please Select Certificate Image!',
  editlanguagesText: 'en_Edit Languages',
  noRecordFoundText: 'en_No Records Found',
  noCertificateFoundText: 'en_No certificates found',
  withInText: 'en_Within',
  ofText: 'en_of',
  generalText: 'en_General',
  peopleTitleText: 'en_People',
  groupsTitleText: 'en_Groups',
  gamesTitleText: 'en_Games',
  postsTitleText: 'en_Posts',
  teamsTitleText: 'en_Teams',
  clubsTitleText: 'en_Clubs',
  leaguesTitleText: 'en_Leagues',
  worldTitleText: 'en_world',
  completedTitleText: 'en_Completed',
  upcomingTitleText: 'en_Upcoming',
  videosTitleText: 'en_Videos',
  photosTitleText: 'en_Photos',
  gameIDNotExitsTitle: 'en_Game ID does not exist.',
  homeCityTitleText: 'en_Home City',
  selectSportTitleText: 'en_Select Sport',
  toText: 'en_To',
  fromText: 'en_From',
  timezoneTitleText: 'en_Time zone',
  areYouSureRemoveFilterText: 'en_Are you sure want to reset filters?',
  okTitleText: 'en_OK',
  resetTitleText: 'en_Reset',
  reservationsTitleText: 'en_Reservations',
  playingTitleText: 'en_Playing',
  refereeingTitleText: 'en_Refereeing',
  scorekeepingTitleText: 'en_Scorekeeping',
  addSportsTitle: 'en_Add a sport',
  registerRefereeTitle: 'en_Register as Referee',
  registerScorekeeperTitle: 'en_Register as Scorekeeper',
  createTeamText: 'en_Create Team',
  createClubText: 'en_Create Club',
  createLeagueText: 'en_Create a League',
  paymentPayoutText: 'en_Payment & Payout',
  paymentMethodTitle: 'en_Payment Method',
  payoutMethodTitle: 'en_Payout Method',
  invoicesTitle: 'en_Invoices',
  transactionsTitles: 'en_Transactions',
  settingsTitleText: 'en_Settings',
  invoicingTitleText: 'en_Invoicing',
  appLanguage: 'en_App Language',
  useDeviceLangTitle: 'en_Use Device Language',
  linkedCopied: 'en_Link Copied!',
  enterThreeCharText: 'en_Please enter atleast 3 characters to see city',
  remove: 'en_Remove',
  noTabsFoundText_dy: 'en_No {0} Found',
  entityCreatedText_dy: 'en_{0}\nhas been created.',
  sportsTitleText: 'en_Sports',
  locationTitleText: 'en_Location',
  addLanguageText: 'en_Add language',
  clubNameText: 'en_Club name',
  homeCityText: 'en_Home city',
  describeText: 'en_Describe',
  player: 'en_Player',
  coach: 'en_Coach',
  othersText: 'en_Others',
  thisFeaturesNotAvailableText:
    'en_This feature is not available (on this device / in this context)',
  minMaxText_dy: 'en_Min {0} Max {1}',
  playerTitleText_dy: 'Player {0}',
  adminText_dy: '{0} Admin',
  doYouWantToRemoText_dy: 'Do you want to remove {0} {1} from {2}?',
  profileHasBeenCreatedText: '{0}’s profile has been created in your {1}.',

  requestDeclinedText: 'en_This request is already declined.',
  requestDeletedText: 'en_This request is already deleted.',
  requestAcceptedText: 'en_This request is already accepted.',
  requestNotValidText: 'en_This request is not valid now.',
  requestStatusNotText: 'en_status not defined',
  goToTeamHomeText: 'en_Go to team home',
  teamMemberShipText: 'en_Team Membership & Admin Authority',
  nameCanNotBlankText: 'en_First name cannot be blank',
  lastNameCanNotBlankText: 'en_Last name cannot be blank',
  emailNotBlankText: 'en_Email cannot be blank',

  connectAccountRequestText:
    'en_sent you a request to connect your account  to one of their exsiting member profiles. When you accept it, you will be a member in the team and the profile will be connected to your account.',
  nameDifferentText:
    'en_If the name on the profile is different from the name on your account, it will be replaced with the name on your account.',

  requestSentText: 'en_Request sent successfully.',

  sendRequestText: 'en_Send request for basic info',
  collectMemberInfoText:
    'en_You can send a request to collect a member’s basic info. When it is accepted, this basic info will be updated with the information provided by the member.',

  adminAuthorityText: 'en_Admin Authority And Role',
  syncInfoText: 'en_Sync Info',
  importMembersText:
    'en_How do you like to update a member’s profile by Importing member’s account info?',
  manually: 'en_Mannually',
  automatically: 'en_Automatically',
  clickSyncButtonText:
    'en_A member’s profile is updated when you click the “sync Info” button in each member’s profile.',

  autoSyncInfoText:
    'en_A member’s profile is updated every time a member changes his or her account info.',
  eachteamSettingNote:
    'en_* Each team settings prevails over the club settings.',
  connectionRequestSentText: 'en_Connection request sent',
  accountConnectText:
    'en_When {0} {1} accepts the request, the user’s account will be connected to the member’s profile created in your group.',

  selectOneMemberText: 'en_Please select one member for connect with profile.',

  inviteBySearchText: 'en_Invite by Search',
  inviteEmailtext: 'en_Invite by E-mail',

  groupMessageText: 'en_Group Message',
  inviteMemberText: 'en_Invite Member',
  createMemberProfileText: 'en_Create Member Profile',
  connectMemberAccountText: 'en_Connect Member Account',
  sendrequestForBaicInfoText: 'en_Send Request For Basic Info',
  setting: 'en_Setting',
  noPlayer: 'en_No Players',
  youCanNotAddMoreEmailText: 'en_You can not add more than 10 email id.',
  send: 'en_Send',
  fillAllEmailText: 'en_Please fill all email fields.',
  configureEmailAccounttext: 'en_Please configure email in your device',
  // entity type for matching only
  entityTypeGame: 'game',
  entityTypeClub: 'club',
  entityTypeTeam: 'team',
  entityTypeUser: 'user',
  entityTypePlayer: 'player',
  entityTypePlayers: 'players',
  entityTypeGroups: 'groups',
  tennisSport: 'tennis',
  doubleSport: 'double',
  tennisDoubleSport: 'Tennis Double',
};
