const PATH = {
  orangeLayer: require('../assets/images/orange_layer.png'),
  signUpBg1: require('../assets/images/ic_signup_bg_1.png'),
  signUpBg2: require('../assets/images/ic_signup_bg_2.png'),
  signUpBg3: require('../assets/images/ic_signup_bg_3.png'),
  townsCupLogo: require('../assets/images/ic_townscup_logo.png'),
  email: require('../assets/images/normal_signup.png'),
  signUpFb: require('../assets/images/signup_fb.png'),
  signUpGoogle: require('../assets/images/signup_google.png'),
  bgImage: require('../assets/images/ic_bg.png'),
  profilePlaceHolder: require('../assets/images/profileplaceholder.png'),
  searchLocation: require('../assets/images/ic_search_orange.png'),
  archerySport: require('../assets/images/ic_archery.png'),
  bandySport: require('../assets/images/ic_Bandy.png'),
  baseballSport: require('../assets/images/ic_Baseball.png'),
  backetballSport: require('../assets/images/ic_Basketball.png'),
  footballSport: require('../assets/images/ic_Basketball.png'),

  checkWhite: require('../assets/images/ic_white_check.png'),
  uncheckWhite: require('../assets/images/ic_white_uncheck.png'),
  checkEditor: require('../assets/images/ic_check_editor.png'),
  uncheckEditor: require('../assets/images/ic_uncheck_editor.png'),

  vertical3Dot: require('../assets/images/ic_dot.png'),
  downArrow: require('../assets/images/ic_down_arrow.png'),
  upArrow: require('../assets/images/ic_up_arrow.png'),
  dropDownArrow: require('../assets/images/down_arrow.png'),
  curruentTime: require('../assets/images/ic_game_curruent_time.png'),
  gamePlus: require('../assets/images/ic_game_plus.png'),
  gameRecord: require('../assets/images/ic_record.png'),
  gamePause: require('../assets/images/ic_game_pause.png'),
  gameStart: require('../assets/images/ic_game_start.png'),
  gameDetail: require('../assets/images/ic_details.png'),
  deleteRecentGoal: require('../assets/images/ic_delete_recent_goal.png'),

  gameYC: require('../assets/images/ic_yc.png'),
  gameRC: require('../assets/images/ic_rc.png'),
  gameGoal: require('../assets/images/ic_goal.png'),
  gameOwnGoal: require('../assets/images/ic_own_goal.png'),
  gameIn: require('../assets/images/ic_in.png'),
  gameOut: require('../assets/images/ic_out.png'),
  feedComment: require('../assets/images/feed_comment.png'),
  feedShare: require('../assets/images/feed_share.png'),
  feedLike: require('../assets/images/feed_like.png'),
  videoPlayerHandle: require('../assets/images/oval.png'),

  groupIcon: require('../assets/images/ic_group.png'),
  club_ph: require('../assets/images/club_profile_placeholder.png'),
  club_ph_selected: require('../assets/images/club_profile_placeholder_selected.png'),

  team_ph: require('../assets/images/team_profile_placeholder.png'),
  group_ph: require('../assets/images/group_ph.png'),
  team_ph_selected: require('../assets/images/team_profile_placeholder_selected.png'),

  tab_newsfeed: require('../assets/images/tab_newsfeed.png'),
  tab_search: require('../assets/images/tab_search.png'),
  tab_home: require('../assets/images/tab_home.png'),
  tab_notification: require('../assets/images/tab_notification.png'),
  tab_account: require('../assets/images/tab_account.png'),
  messageBox_account: require('../assets/images/ic_message_box.png'),
  nextArrow: require('../assets/images/ic_next_arrow.png'),

  certificateUpload: require('../assets/images/ic_img_upload.png'),
  noImagePH: require('../assets/images/no_image.png'),

  radioSelect: require('../assets/images/ic_radio_select.png'),
  radioUnselect: require('../assets/images/ic_radio_unselect.png'),

  backArrow: require('../assets/images/back_arrow.png'),
};

export default PATH;
