/* eslint-disable global-require */
const images = {
  orangeLayer: require('../assets/images/orange_layer.png'),
  townsCupLogo: require('../assets/images/ic_townscup_logo.png'),

  hidePassword: require('../assets/images/ic_hidepassword.png'),
  showPassword: require('../assets/images/ic_showpassword.png'),

  email: require('../assets/images/normal_signup.png'),
  signUpFb: require('../assets/images/signup_fb.png'),
  signUpGoogle: require('../assets/images/signup_google.png'),
  bgImage: require('../assets/images/ic_bg.png'),
  entityCreatedBG: require('../assets/images/entity_created_bg.png'),
  searchUser: require('../assets/images/searchUser.png'),
  profilePlaceHolder: require('../assets/images/profileplaceholder.png'),
  dummyPhoto: require('../assets/images/dummy_photo.png'),
  searchLocation: require('../assets/images/ic_search_orange.png'),
  chatSearch: require('../assets/images/chatSearch.png'),

  archerySport: require('../assets/images/ic_archery.png'),
  bandySport: require('../assets/images/ic_Bandy.png'),
  baseballSport: require('../assets/images/ic_Baseball.png'),
  backetballSport: require('../assets/images/ic_Basketball.png'),
  footballSport: require('../assets/images/ic_Basketball.png'),

  checkWhite: require('../assets/images/ic_white_check.png'),
  check: require('../assets/images/check.png'),
  checkGreen: require('../assets/images/green_check.png'),
  radioCheckYellow: require('../assets/images/radioSelectYellow.png'),
  whiteUncheck: require('../assets/images/white_uncheck.png'),
  uncheckWhite: require('../assets/images/ic_white_uncheck.png'),
  checkEditor: require('../assets/images/ic_check_editor.png'),
  uncheckEditor: require('../assets/images/ic_uncheck_editor.png'),

  gamesImage: require('../assets/images/Games_Image.png'),
  assistsImage: require('../assets/images/Assists_Image.png'),
  goalsImage: require('../assets/images/Goals_Image.png'),
  yellowCardImage: require('../assets/images/YellowCard_Image.png'),
  gamesSelected: require('../assets/images/Games_Select.png'),
  assistsSelected: require('../assets/images/Assists_Select.png'),
  goalsSelected: require('../assets/images/Goals_Select.png'),
  yellowCardSelected: require('../assets/images/Yellow_Card_Select.png'),

  groupIcon: require('../assets/images/ic_group.png'),
  club_ph: require('../assets/images/club_profile_placeholder.png'),
  newClubIcon: require('../assets/images/newClubIcon.png'),
  team_ph: require('../assets/images/team_profile_placeholder.png'),
  tab_home: require('../assets/images/tab_home.png'),
  tab_notification: require('../assets/images/tab_notification.png'),
  tab_account: require('../assets/images/tab_account.png'),
  nextArrow: require('../assets/images/ic_next_arrow.png'),
  calNextArrow: require('../assets/images/cal_next.png'),
  calPrevArrow: require('../assets/images/cal_prev.png'),

  backArrow: require('../assets/images/ic_back_arrow.png'),
  menu: require('../assets/images/menu.png'),
  threeDotIcon: require('../assets/images/three_dot_icon.png'),
  chat3Dot: require('../assets/images/chat3Dot.png'),
  scheduleThreeDot: require('../assets/images/scheduleThreeDot.png'),
  vertical3Dot: require('../assets/images/ic_dot.png'),
  horizontal3Dot: require('../assets/images/ic_horizontal_dot.png'),
  downArrow: require('../assets/images/ic_down_arrow.png'),
  dropDownArrow: require('../assets/images/down_arrow.png'),
  path: require('../assets/images/Path.png'),

  dropDownArrow2: require('../assets/images/down_arrow.png'),
  curruentTime: require('../assets/images/ic_game_curruent_time.png'),
  gamePlus: require('../assets/images/ic_game_plus.png'),
  gameOrangePlus: require('../assets/images/game_rocord.png'),
  gameRecord: require('../assets/images/ic_record.png'),
  gamePause: require('../assets/images/ic_game_pause.png'),
  gameStart: require('../assets/images/ic_game_start.png'),
  gameDetail: require('../assets/images/ic_details.png'),
  gameSimple: require('../assets/images/ic_game_simple.png'),
  deleteRecentGoal: require('../assets/images/ic_delete_recent_goal.png'),
  deleteIcon: require('../assets/images/delete.png'),
  roundArrow: require('../assets/images/roundArrow.png'),
  gameYC: require('../assets/images/ic_yc.png'),
  gameRC: require('../assets/images/ic_rc.png'),
  gameGoal: require('../assets/images/ic_goal.png'),
  gameOwnGoal: require('../assets/images/ic_own_goal.png'),
  gameIn: require('../assets/images/ic_in.png'),
  gameOut: require('../assets/images/ic_out.png'),
  feedComment: require('../assets/images/feed_comment.png'),
  feedShare: require('../assets/images/feed_share.png'),
  feedLike: require('../assets/images/feed_like.png'),
  lock: require('../assets/images/lock.png'),
  pickImage: require('../assets/images/pick_image.png'),
  commentReport: require('../assets/images/comment_report.png'),
  tagImage: require('../assets/images/tag.png'),
  tagGreenImage: require('../assets/images/Tag_Icon.png'),
  cancelImage: require('../assets/images/cancel.png'),
  crossImage: require('../assets/images/cross.png'),

  createEventImage: require('../assets/images/create_event_image.png'),
  cancelWhite: require('../assets/images/cancelWhite.png'),
  tab_home_selected: require('../assets/images/tab_home_selected.png'),

  landscapeTopImage: require('../assets/images/Landscape_Top.png'),
  landscapeBottomImage: require('../assets/images/Landscape_Bottom.png'),

  portraitVideoImage: require('../assets/images/Portrait_Video_Image.png'),
  landscapeVideoImage: require('../assets/images/Landscape_Video_Image.png'),

  tab_reservation: require('../assets/images/tab_reservation.png'),
  tab_reservation_selected: require('../assets/images/tab_reservation_selected.png'),

  tab_notification_selected: require('../assets/images/tab_notification_selected.png'),

  tab_message: require('../assets/images/tab_messages.png'),
  tab_message_selected: require('../assets/images/tab_selected_messages.png'),

  tab_members: require('../assets/images/tab_members.png'),
  tab_members_selected: require('../assets/images/tab_selected_members.png'),

  tab_account_selected: require('../assets/images/tab_account_selected.png'),

  tab_account_group: require('../assets/images/tab_account_group.png'),
  tab_account_group_selected: require('../assets/images/tab_account_group_selected.png'),

  certificateUpload: require('../assets/images/ic_img_upload.png'),
  certiImagePick: require('../assets/images/certi_image_pick.png'),

  radioSelect: require('../assets/images/ic_radio_select.png'),
  plus: require('../assets/images/plus.png'),
  plusInvoice: require('../assets/images/plus_invoice.png'),
  multipleImagesIcon: require('../assets/images/multiple_images.png'),
  radioUnselect: require('../assets/images/ic_radio_unselect.png'),

  dotImage: require('../assets/images/ic_dot.png'),
  mute: require('../assets/images/mute.png'),
  videoPlayBtn: require('../assets/images/video_play_button.png'),
  unmute: require('../assets/images/unmute.png'),
  videoPlayButton: require('../assets/images/video_play_btn.png'),
  videoPauseButton: require('../assets/images/video_pause_btn.png'),

  commentImage: require('../assets/images/msg_icon.png'),
  shareImage: require('../assets/images/share_icon.png'),
  likeImage: require('../assets/images/like_icon.png'),
  unlikeImage: require('../assets/images/unlike_icon.png'),

  shortComment: require('../assets/images/short_comment.png'),
  shortShare: require('../assets/images/short_share.png'),
  shortDisLike: require('../assets/images/short_dislike.png'),
  shortLike: require('../assets/images/short_like.png'),

  checkWhiteLanguage: require('../assets/images/ic_white_check_language.png'),
  mySchedule: require('../assets/images/My_Schedule.png'),
  mySports: require('../assets/images/My_Sports.png'),
  myRefereeing: require('../assets/images/My_Refereeing.png'),
  myScoreKeeping: require('../assets/images/scorekeeper_in.png'),
  myTeams: require('../assets/images/My_Teams.png'),
  newTeamIcon: require('../assets/images/newTeamIcon.png'),
  myClubs: require('../assets/images/My_Clubs.png'),
  myLeagues: require('../assets/images/My_Leagues.png'),
  paymentPayout: require('../assets/images/PaymentPayout.png'),
  SettingPrivacy: require('../assets/images/SettingPrivacy.png'),
  refereesInImage: require('../assets/images/referees_in_image.png'),
  Members: require('../assets/images/members.png'),

  // Account Screen Icons
  accountMySchedule: require('../assets/images/accountMySchedule.png'),
  accountMyReservations: require('../assets/images/accountReservations.png'),
  accountMySports: require('../assets/images/accountMySports.png'),
  accountMyRefereeing: require('../assets/images/accountMyRefereeing.png'),
  accountMyScoreKeeping: require('../assets/images/accountMyScoreKeeping.png'),
  accountMyTeams: require('../assets/images/accountMyTeams.png'),
  accountMyClubs: require('../assets/images/accountMyClubs.png'),
  accountMyLeagues: require('../assets/images/accountMyTeams.png'),
  accountPaymentPayout: require('../assets/images/accountPaymentPayout.png'),
  accountSettingPrivacy: require('../assets/images/accountSettingPrivacy.png'),
  // accountMembers: require('../assets/images/accountMembers.png'),

  createTeam: require('../assets/images/Create_a_team.png'),
  createClub: require('../assets/images/Create_a_club.png'),
  createLeague: require('../assets/images/Create_a_league.png'),
  addSport: require('../assets/images/Add_a_sport.png'),
  registerReferee: require('../assets/images/Register_as_a_referee.png'),
  registerScorekeeper: require('../assets/images/Register_as_a_scorekeeper.png'),

  switchAccount: require('../assets/images/switch_account.png'),
  teamPlaceholder: require('../assets/images/team_placeholder.png'),
  newTeamPlaceHolder: require('../assets/images/newTeamPlaceHolder.png'),
  teamBcgPlaceholder: require('../assets/images/team_bcg_placeHolder.png'),
  tennisArrowRight: require('../assets/images/tennis_arrow_right.png'),
  tennisArrowLeft: require('../assets/images/tennis_arrow_left.png'),
  noSpecicPlayer: require('../assets/images/ic_no_specific.png'),
  clubPlaceholder: require('../assets/images/club_placeholder.png'),
  clubBcgPlaceholder: require('../assets/images/club_bcg_placeHolder.png'),
  leaguePlaceholder: require('../assets/images/league_placeholder.png'),
  teamPlaceholderSmall: require('../assets/images/teamplaceholder.png'),
  clubPlaceholderSmall: require('../assets/images/clubplaceholder.png'),

  usaImage: require('../assets/images/NewYorkCityFC.png'),

  Payout_method: require('../assets/images/Payout_method.png'),
  Transations: require('../assets/images/Transations.png'),
  Payment_method: require('../assets/images/Payment_method.png'),
  Invoicing: require('../assets/images/Invoicing.png'),

  clubLable: require('../assets/images/club_lable.png'),
  clubSqure: require('../assets/images/club_squre.png'),
  teamSqure: require('../assets/images/team_squre.png'),

  logoutIcon: require('../assets/images/logout_icon.png'),

  basketballLoader: require('../assets/images/basketball_loader.png'),
  soccerLoader: require('../assets/images/soccer_loader.png'),
  volleyballLoader: require('../assets/images/volleyball_loader.png'),
  baseballLoader: require('../assets/images/baseball_loader.png'),
  badmintonLoader: require('../assets/images/badminton_loader.png'),
  footballLoader: require('../assets/images/football_loader.png'),
  football2Loader: require('../assets/images/football2_loader.png'),
  imageLoadingGIF: require('../assets/images/image_loading.gif'),
  imageUploadingGIF: require('../assets/images/loadingGIF.gif'),

  soccerImage: require('../assets/images/soccerImage.png'),

  // Reservation Component
  requestIn: require('../assets/images/request_in.png'),
  requestOut: require('../assets/images/request_out.png'),
  dottedLine: require('../assets/images/dotLine.png'),

  // members
  arrowGraterthan: require('../assets/images/arrow_graterthan.png'),
  teamT: require('../assets/images/team_T.png'),
  clubC: require('../assets/images/club_C.png'),
  leagueL: require('../assets/images/league_L.png'),
  editSection: require('../assets/images/ic_edit.png'),
  tagDivider: require('../assets/images/tag_divider.png'),
  chain: require('../assets/images/chain.png'),
  emailSent1: require('../assets/images/InvitationEmail1.png'),
  emailSent2: require('../assets/images/InvitationEmail2.png'),
  emailSent3: require('../assets/images/InvitationEmail3.png'),
  emailSent4: require('../assets/images/InvitationEmail4.png'),
  emailSent5: require('../assets/images/InvitationEmail5.png'),

  declineChallenge: require('../assets/images/decline_challenge_icon.png'),

  // create member profile
  checkGreenBG: require('../assets/images/check_green_bg.png'),
  editButton: require('../assets/images/edit_button.png'),

  radioUnSelectGreen: require('../assets/images/uncheck_no_tick.png'),
  radioSelectGreen: require('../assets/images/check_green_tick.png'),
  menuClose: require('../assets/images/menu_close.png'),
  closeSearch: require('../assets/images/close_search.png'),
  closeRound: require('../assets/images/close_round.png'),
  // create challenge
  swapTeam: require('../assets/images/swap_team.png'),
  radioCheckGreenBG: require('../assets/images/radio_check_green_bg.png'),

  // Message Module
  messageCamera: require('../assets/images/messageCamera.png'),
  sendButton: require('../assets/images/sendButton.png'),
  groupUsers: require('../assets/images/groupUsers.png'),
  plus_round_orange: require('../assets/images/plus_round_orange.png'),

  // Game Module
  leave_chat_room: require('../assets/images/leave_chat_room.png'),
  soccerBackground: require('../assets/images/soccerBackground.png'),
  warningIcon: require('../assets/images/warning.png'),
  popupUpArrow: require('../assets/images/topPopupArrow.png'),
  assistBy: require('../assets/images/assistBy.png'),
  assistReferee: require('../assets/images/Assist_Referee.png'),
  blankRatingStar: require('../assets/images/blankRatingStar.png'),
  yellowRatingStar: require('../assets/images/yellowRatingStar.png'),
  blueRatingStar: require('../assets/images/blueRatingStar.png'),
  greenRatingStar: require('../assets/images/greenRatingStar.png'),
  moveFlottyButton: require('../assets/images/move_flotty_btn.png'),
  orangeGradient: require('../assets/images/orangeGradient.png'),
  themeGradientImage: require('../assets/images/theme_gradient.png'),
  thumbImage: require('../assets/images/thumbImage.png'),
  tennisBackground: require('../assets/images/tennisBackground.png'),
  leagueDemo: require('../assets/images/leaguedemo.png'),
  whiteTrophySmall: require('../assets/images/minitropy.png'),
  editPencil: require('../assets/images/editPencil.png'),
  addRole: require('../assets/images/add_activity.png'),
  tennisAce: require('../assets/images/ic_tennis_ace.png'),
  tennisFault: require('../assets/images/tennisFault.png'),
  tennisFootFault: require('../assets/images/tennisFootFault.png'),
  tennisScore: require('../assets/images/tennisScore.png'),
  tennisLet: require('../assets/images/tennisLet.png'),
  tennisUnForced: require('../assets/images/tennisUnForced.png'),
  tennisWinner: require('../assets/images/tennisWinner.png'),
  yellowDownArrow: require('../assets/images/yellowDownArrow.png'),
  refereeSucessBG: require('../assets/images/RefereeSucessBG.png'),
  playerSucessBG: require('../assets/images/playerSucessBG.png'),

  // Tennis recorder
  tennisGeneral: require('../assets/images/ic_tennis_general.png'),
  requestSentImage: require('../assets/images/requestSentImage.png'),
  whiteTick: require('../assets/images/whiteTick.png'),
  undoImage: require('../assets/images/undo.png'),
  tennisSingleHeaderIcon: require('../assets/images/tennisSingleHeaderIcon.png'),
  orangeCheckBox: require('../assets/images/orangeCheckBox.png'),
  radioSelectYellow: require('../assets/images/radioSelectYellow.png'),
  referePH: require('../assets/images/referee_placeholder.png'),
  scorekeeperPH: require('../assets/images/scorekeeper_placeholder.png'),
  notificationBell: require('../assets/images/notification_bell.png'),
  tabFeed: require('../assets/images/tab_feed.png'),
  tabSelectedFeed: require('../assets/images/tab_selected_feed.png'),

  teamPatch: require('../assets/images/team_patch.png'),
  clubPatch: require('../assets/images/club_patch.png'),
  leaguePatch: require('../assets/images/league_patch.png'),

  townsCupIcon: require('../assets/images/tc_icon.png'),
  home_search: require('../assets/images/ic_search.png'),
  home_gps: require('../assets/images/ic_gps.png'),

  home_setting: require('../assets/images/ic_setting.png'),
  orangeStar: require('../assets/images/ic_star.png'),

  homeSetting: require('../assets/images/ic_home_setting.png'),
  settingInvoice: require('../assets/images/setting_invoice.png'),

  arrowDown: require('../assets/images/arrow_down.png'),
  moveIcon: require('../assets/images/ic_move.png'),
  checkRoundOrange: require('../assets/images/check_radio_orange.png'),
  radioRoundOrange: require('../assets/images/check_radio_orange.png'),

  addStatus: require('../assets/images/add_status.png'),
  addMessageChat: require('../assets/images/addMessageChat.png'),
  greenQBGroup: require('../assets/images/greenQBGroup.png'),
  greenQBUser: require('../assets/images/greenQBUser.png'),
  yellowQBGroup: require('../assets/images/yellowQBGroup.png'),
  yellowQBUser: require('../assets/images/yellowQBUser.png'),
  messageSearchButton: require('../assets/images/messageSearchButton.png'),
  messageSearchButton2: require('../assets/images/messageSearchButton2.png'),
  yellowCheckBox: require('../assets/images/yellowCheckBox.png'),
  tc_message_top_icon: require('../assets/images/tc_message_top_icon.png'),
  welcomeImage1: require('../assets/images/welcomeImage1.png'),
  welcomeImage2: require('../assets/images/welcomeImage2.png'),
  welcomeImage3: require('../assets/images/welcomeImage3.png'),
  welcomeImage4: require('../assets/images/welcomeImage4.png'),
  loginBg: require('../assets/images/loginBg.png'),
  emailSendIconBG: require('../assets/images/emailSendIconBG.png'),
  feedPlusIcon: require('../assets/images/feedPlusIcon.png'),
  resetColor: require('../assets/images/reset_color.png'),
  appleLogo: require('../assets/images/appleLogo.png'),
  timeKnobGray: require('../assets/images/time_knob_gray.png'),
  timeKnobOrange: require('../assets/images/time_knob_orange.png'),

  grayListIcon: require('../assets/images/gray_list_icon.png'),
  orangeListIcon: require('../assets/images/orange_list_icon.png'),
  linkCopied: require('../assets/images/linkCopied.png'),
  galleryVideoIcon: require('../assets/images/galleryVideoIcon.png'),
  videoPauseIcon: require('../assets/images/videoPauseIcon.png'),
  videoPlayIcon: require('../assets/images/videoPlayIcon.png'),
  videoFullScreen: require('../assets/images/videoFullScreen.png'),
  videoMuteSound: require('../assets/images/videoMuteSound.png'),
  videoNormalScreen: require('../assets/images/videoNormalScreen.png'),
  videoUnMuteSound: require('../assets/images/videoUnMuteSound.png'),
  videoThumb: require('../assets/images/videoThumb.png'),
  videoLoading: require('../assets/images/videoLoading.gif'),
  unCheckWhiteBorder: require('../assets/images/unCheckWhiteBorder.png'),

  teamGreenPH: require('../assets/images/team_green_ph.png'),

  menuGray: require('../assets/images/menu_gray.png'),
  menuOrange: require('../assets/images/menu_orange.png'),
  scheduleGray: require('../assets/images/schedule_ic_gray.png'),
  scheduleOrange: require('../assets/images/schedule_ic_orange.png'),
  feedViewLikeButton: require('../assets/images/feedViewLikeButton.png'),
  feedViewUnLike: require('../assets/images/feedViewUnLike.png'),
  feedViewCommentButton: require('../assets/images/feedViewCommentButton.png'),
  feedViewShareButton: require('../assets/images/feedViewShareButton.png'),

  doubleTeamCreated: require('../assets/images/double_team_created.png'),
  challengeSentPlane: require('../assets/images/challenge_sent_plane.png'),
  likePlay: require('../assets/images/likePlay.png'),
  manageChallengeIcon: require('../assets/images/manage_challenge.png'),
  infoToolTipIcon: require('../assets/images/info_icon.png'),

  challengerFlag: require('../assets/images/challenger_flag.png'),
  challengeeCup: require('../assets/images/challengee_cup.png'),
  teamPH: require('../assets/images/team_PH.png'),

  clubSmallIcon: require('../assets/images/clubSmallIcon.png'),
  teamSmallIcon: require('../assets/images/teamSmallIcon.png'),
  leagueSmallIcon: require('../assets/images/leagueSmallIcon.png'),

  clubCover: require('../assets/images/clubCover.png'),
  leagueCover: require('../assets/images/leagueCover.png'),
  teamCover: require('../assets/images/teamCover.png'),

  selectAddMessageButton: require('../assets/images/selectAddMessageButton.png'),
  selectMessageSearchButton: require('../assets/images/selectMessageSearchButton.png'),
  challengerInvitePlane: require('../assets/images/challenger_invite_plane.png'),
  savedIcon: require('../assets/images/savedIcon.png'),
  arrowGT: require('../assets/images/arrow_gt.png'),

  messageIcon: require('../assets/images/message_ic.png'),
  navigationBack: require('../assets/images/navigation_back.png'),

  newFeed: require('../assets/images/new_feed.png'),
  messageCheckboxBorder: require('../assets/images/messageCheckboxBorder.png'),
  youtubePlayButton: require('../assets/images/youtubePlayButton.png'),
  smallRight: require('../assets/images/smallRight.png'),
  commentDeleteIcon: require('../assets/images/commentDeleteIcon.png'),
  commentReportIcon: require('../assets/images/commentReportIcon.png'),

  //  Sports Icons
  soccerIcon: require('../assets/images/soccerIcon.png'),
  tennisIcon: require('../assets/images/tennisIcon.png'),

  backgroundGrayPlceholder: require('../assets/images/background_placeholder.png'),

  challengerBadge: require('../assets/images/challenger_badge.png'),
  challengeeBadge: require('../assets/images/challengee_badge.png'),

  reqIcon: require('../assets/images/req.png'),
  refIcon: require('../assets/images/ref.png'),
  reqeIcon: require('../assets/images/reqe.png'),

  localhomeOverlay: require('../assets/images/opacitylayer_localhome.png'),
  orangeGradiet: require('../assets/images/orange_gradient.png'),
  greenGradient: require('../assets/images/green_gradient.png'),
  blueGradient: require('../assets/images/blue_gradient.png'),
  uncheckBox: require('../assets/images/uncheckBox.png'),
  profileLevel: require('../assets/images/profile_level.png'),
  chatPlus: require('../assets/images/chat_plus.png'),
  recentMatch: require('../assets/images/recentMatch.png'),
  upcomingMatch: require('../assets/images/upcomingMatch.png'),
  shortCard: require('../assets/images/shortCard.png'),
  settingSport: require('../assets/images/settingSport.png'),

  addEvent: require('../assets/images/add_event.png'),
  playerIcon: require('../assets/images/player_ic.png'),

  refereeIcon: require('../assets/images/referee_ic.png'),

  scorekeeperIcon: require('../assets/images/scorekeeper_ic.png'),
  localHomeFilter: require('../assets/images/Filter.png'),

  addSportList: require('../assets/images/add_sport_list.png'),
  removeSportList: require('../assets/images/remove_sport_list.png'),
  choosePic: require('../assets/images/choose_pic.png'),

  availableChallenge: require('../assets/images/available_challenge.png'),
  blockedChallenge: require('../assets/images/blocked_challenge.png'),
  backgroudPlaceholder: require('../assets/images/backgroudPlaceholder.png'),
  backgroundPlaceholder: require('../assets/images/backgroudPlaceholder.png'),
  moreIcon: require('../assets/images/moreIcon.png'),

  downloadImage: require('../assets/images/download_icon.png'),
  deleteImage: require('../assets/images/deleteImage_icon.png'),
  inviteEmail: require('../assets/images/inviteEmail.png'),
  copyUrl: require('../assets/images/copyUrl.png'),
  createMember: require('../assets/images/createMember.png'),
  unlinked: require('../assets/images/unlinked.png'),
  createTeamRoundIcon: require('../assets/images/createTeam.png'),
  invoiceIcon: require('../assets/images/invvoice.png'),
  scoreBoardBackgroundImage: require('../assets/images/scoreboardBg.png'),
  moreOptions: require('../assets/images/moreOptions.png'),
  infoIcon: require('../assets/images/infoIcon.png'),
  clubPatchIcon: require('../assets/images/clubPatch.png'),
  teamPatchIcon: require('../assets/images/teamPatch.png'),
  editProfilePencil: require('../assets/images/EditprofilePencil.png'),
  activityImage: require('../assets/images/activityImage.png'),
  activityImage1: require('../assets/images/activityImage1.png'),
  activityImage2: require('../assets/images/activityImage2.png'),

  // Events
  challengeDefault: require('../assets/images/challenge_default.png'),
  eventDefault: require('../assets/images/event_default.png'),
  leftArrow: require('../assets/images/left_arrow.png'),
  rightArrow: require('../assets/images/right_arrow.png'),
  toggleCal: require('../assets/images/toggle_cal.png'),
  eventClock: require('../assets/images/event_clock.png'),
  eventMap: require('../assets/images/event_map.png'),
  roundTick: require('../assets/images/round_tick.png'),
  roundCross: require('../assets/images/round_cross.png'),
  whiteBackArrow: require('../assets/images/whiteBackArrow.png'),
  white3Dots: require('../assets/images/white3Dots.png'),
  crossSingle: require('../assets/images/cross-single.png'),
  certificateCamera: require('../assets/images/certificateCamera.png'),
  refreshIcon: require('../assets/images/refreshIcon.png'),
  noScoreboardImage: require('../assets/images/noScoreboardImage.png'),
  lookingForImg: require('../assets/images/lookingForImg.png'),
  toggleList: require('../assets/images/toggle_list.png'),

  calenderToggle: require('../assets/images/upper-arrow.png'),
  xCircleImg: require('../assets/images/xCircle.png'),
};

export default images;
