/* eslint-disable global-require */
const images = {
  orangeLayer: require('../assets/images/orange_layer.png'),
  signUpBg1: require('../assets/images/ic_signup_bg_1.png'),
  signUpBg2: require('../assets/images/ic_signup_bg_2.png'),
  signUpBg3: require('../assets/images/ic_signup_bg_3.png'),
  townsCupLogo: require('../assets/images/ic_townscup_logo.png'),

  hidePassword: require('../assets/images/ic_hidepassword.png'),
  showPassword: require('../assets/images/ic_showpassword.png'),

  email: require('../assets/images/normal_signup.png'),
  signUpFb: require('../assets/images/signup_fb.png'),
  signUpGoogle: require('../assets/images/signup_google.png'),
  bgImage: require('../assets/images/ic_bg.png'),
  searchUser: require('../assets/images/searchUser.png'),
  profilePlaceHolder: require('../assets/images/profileplaceholder.png'),
  searchLocation: require('../assets/images/ic_search_orange.png'),
  archerySport: require('../assets/images/ic_archery.png'),
  bandySport: require('../assets/images/ic_Bandy.png'),
  baseballSport: require('../assets/images/ic_Baseball.png'),
  backetballSport: require('../assets/images/ic_Basketball.png'),
  footballSport: require('../assets/images/ic_Basketball.png'),

  checkWhite: require('../assets/images/ic_white_check.png'),
  check: require('../assets/images/check.png'),
  checkGreen: require('../assets/images/green_check.png'),
  whiteUncheck: require('../assets/images/white_uncheck.png'),
  moveButton: require('../assets/images/move_btn.png'),
  uncheckWhite: require('../assets/images/ic_white_uncheck.png'),
  checkEditor: require('../assets/images/ic_check_editor.png'),
  uncheckEditor: require('../assets/images/ic_uncheck_editor.png'),

  gamesImage: require('../assets/images/Games_Image.png'),
  assistsImage: require('../assets/images/Assists_Image.png'),
  goalsImage: require('../assets/images/Goals_Image.png'),
  yellowCardImage: require('../assets/images/YellowCard_Image.png'),
  gamesSelected: require('../assets/images/Games_Select.png'),
  assistsSelected: require('../assets/images/Assists_Select.png'),
  goalsSelected: require('../assets/images/Goals_Select.png'),
  yellowCardSelected: require('../assets/images/Yellow_Card_Select.png'),

  groupIcon: require('../assets/images/ic_group.png'),
  club_ph: require('../assets/images/club_profile_placeholder.png'),
  team_ph: require('../assets/images/team_profile_placeholder.png'),
  tab_newsfeed: require('../assets/images/tab_newsfeed.png'),
  tab_search: require('../assets/images/tab_search.png'),
  tab_home: require('../assets/images/tab_home.png'),
  tab_notification: require('../assets/images/tab_notification.png'),
  tab_account: require('../assets/images/tab_account.png'),
  messageBox_account: require('../assets/images/ic_message_box.png'),
  nextArrow: require('../assets/images/ic_next_arrow.png'),
  backArrow: require('../assets/images/ic_back_arrow.png'),
  menu: require('../assets/images/menu.png'),
  threeDotIcon: require('../assets/images/three_dot_icon.png'),
  vertical3Dot: require('../assets/images/ic_dot.png'),
  horizontal3Dot: require('../assets/images/ic_horizontal_dot.png'),
  downArrow: require('../assets/images/ic_down_arrow.png'),
  upArrow: require('../assets/images/ic_up_arrow.png'),
  dropDownArrow: require('../assets/images/down_arrow.png'),
  dropDownArrow2: require('../assets/images/down_arrow.png'),
  curruentTime: require('../assets/images/ic_game_curruent_time.png'),
  gamePlus: require('../assets/images/ic_game_plus.png'),
  gameRecord: require('../assets/images/ic_record.png'),
  gamePause: require('../assets/images/ic_game_pause.png'),
  gameStart: require('../assets/images/ic_game_start.png'),
  gameDetail: require('../assets/images/ic_details.png'),
  deleteRecentGoal: require('../assets/images/ic_delete_recent_goal.png'),
  deleteIcon: require('../assets/images/delete.png'),
  roundArrow: require('../assets/images/roundArrow.png'),
  gameYC: require('../assets/images/ic_yc.png'),
  gameRC: require('../assets/images/ic_rc.png'),
  gameGoal: require('../assets/images/ic_goal.png'),
  gameOwnGoal: require('../assets/images/ic_own_goal.png'),
  gameIn: require('../assets/images/ic_in.png'),
  gameOut: require('../assets/images/ic_out.png'),
  feedComment: require('../assets/images/feed_comment.png'),
  feedShare: require('../assets/images/feed_share.png'),
  feedLike: require('../assets/images/feed_like.png'),
  lock: require('../assets/images/lock.png'),
  pickImage: require('../assets/images/pick_image.png'),
  commentReport: require('../assets/images/comment_report.png'),
  tagImage: require('../assets/images/tag.png'),
  cancelImage: require('../assets/images/cancel.png'),
  createEventImage: require('../assets/images/create_event_image.png'),
  challengeAvailableImage: require('../assets/images/challenge_available_image.png'),
  cancelWhite: require('../assets/images/cancelWhite.png'),
  videoPlayerHandle: require('../assets/images/oval.png'),
  tab_home_selected: require('../assets/images/tab_home_selected.png'),

  tab_reservation: require('../assets/images/tab_reservation.png'),
  tab_reservation_selected: require('../assets/images/tab_reservation_selected.png'),

  tab_notification_selected: require('../assets/images/tab_notification_selected.png'),

  tab_message: require('../assets/images/tab_messages.png'),
  tab_message_selected: require('../assets/images/tab_messages_selected.png'),

  tab_account_selected: require('../assets/images/tab_account_selected.png'),

  tab_account_group: require('../assets/images/tab_account_group.png'),
  tab_account_group_selected: require('../assets/images/tab_account_group_selected.png'),

  certificateUpload: require('../assets/images/ic_img_upload.png'),
  noImagePH: require('../assets/images/no_image.png'),

  radioSelect: require('../assets/images/ic_radio_select.png'),
  plus: require('../assets/images/plus.png'),
  multipleImagesIcon: require('../assets/images/multiple_images.png'),
  radioUnselect: require('../assets/images/ic_radio_unselect.png'),

  dotImage: require('../assets/images/ic_dot.png'),
  footplayer: require('../assets/images/footballPlayer.png'),
  footballGround: require('../assets/images/footballGround.png'),
  comment: require('../assets/images/comment.png'),
  share: require('../assets/images/share.png'),
  mute: require('../assets/images/mute.png'),
  videoPlayBtn: require('../assets/images/video_play_button.png'),
  unmute: require('../assets/images/unmute.png'),
  playPause: require('../assets/images/play_pause.png'),
  exitGrey: require('../assets/images/exitGrey.png'),
  gallaryImage: require('../assets/images/image.png'),
  bagTick: require('../assets/images/bagTick.png'),
  attatchmentGrey: require('../assets/images/attachmentGrey.png'),
  // likeOrange: require('../assets/images/orangeLike.png'),

  checkWhiteLanguage: require('../assets/images/ic_white_check_language.png'),
  mySchedule: require('../assets/images/My_Schedule.png'),
  mySports: require('../assets/images/My_Sports.png'),
  myRefereeing: require('../assets/images/My_Refereeing.png'),
  myTeams: require('../assets/images/My_Teams.png'),
  myClubs: require('../assets/images/My_Clubs.png'),
  myLeagues: require('../assets/images/My_Leagues.png'),
  paymentPayout: require('../assets/images/PaymentPayout.png'),
  SettingPrivacy: require('../assets/images/SettingPrivacy.png'),
  Members: require('../assets/images/members.png'),

  createTeam: require('../assets/images/Create_a_team.png'),
  createClub: require('../assets/images/Create_a_club.png'),
  createLeague: require('../assets/images/Create_a_league.png'),
  addSport: require('../assets/images/Add_a_sport.png'),
  registerReferee: require('../assets/images/Register_as_a_referee.png'),

  switchAccount: require('../assets/images/switch_account.png'),
  teamPlaceholder: require('../assets/images/team_placeholder.png'),
  clubPlaceholder: require('../assets/images/club_placeholder.png'),
  leaguePlaceholder: require('../assets/images/league_placeholder.png'),
  teamPlaceholderSmall: require('../assets/images/teamplaceholder.png'),
  clubPlaceholderSmall: require('../assets/images/clubplaceholder.png'),

  usaImage: require('../assets/images/NewYorkCityFC.png'),
  chelseaFCImage: require('../assets/images/chelseaFC.png'),
  FCBarcelonaImage: require('../assets/images/FCBarcelona.png'),
  uefaChampionsImage: require('../assets/images/UEFAChampionsLeague.png'),

  Payout_method: require('../assets/images/Payout_method.png'),
  Transations: require('../assets/images/Transations.png'),
  Payment_method: require('../assets/images/Payment_method.png'),
  Invoicing: require('../assets/images/Invoicing.png'),

  clubLable: require('../assets/images/club_lable.png'),
  clubSqure: require('../assets/images/club_squre.png'),
  teamSqure: require('../assets/images/team_squre.png'),

  logoutIcon: require('../assets/images/logout_icon.png'),

  allSportLoader: require('../assets/images/all_sport_loader.png'),
  basketballLoader: require('../assets/images/basketball_loader.png'),
  soccerLoader: require('../assets/images/soccer_loader.png'),
  volleyballLoader: require('../assets/images/volleyball_loader.png'),
  baseballLoader: require('../assets/images/baseball_loader.png'),
  badmintonLoader: require('../assets/images/badminton_loader.png'),
  footballLoader: require('../assets/images/football_loader.png'),
  football2Loader: require('../assets/images/football2_loader.png'),
  imageLoadingGIF: require('../assets/images/image_loading.gif'),
  imageUploadingGIF: require('../assets/images/imageUploadingLoader.gif'),

  soccerImage: require('../assets/images/soccerImage.png'),

  // Reservation Component
  requestIn: require('../assets/images/request_in.png'),
  requestOut: require('../assets/images/request_out.png'),
  dottedLine: require('../assets/images/dotLine.png'),

  // members
  filterIcon: require('../assets/images/ic_filter.png'),
  arrowGraterthan: require('../assets/images/arrow_graterthan.png'),
  teamT: require('../assets/images/team_T.png'),
  clubC: require('../assets/images/club_C.png'),
  editSection: require('../assets/images/ic_edit.png'),
  tagDivider: require('../assets/images/tag_divider.png'),
  chain: require('../assets/images/chain.png'),
  emailSent1: require('../assets/images/InvitationEmail1.png'),
  emailSent2: require('../assets/images/InvitationEmail2.png'),
  emailSent3: require('../assets/images/InvitationEmail3.png'),
  emailSent4: require('../assets/images/InvitationEmail4.png'),
  emailSent5: require('../assets/images/InvitationEmail5.png'),

  declineChallenge: require('../assets/images/decline_challenge_icon.png'),

  // create member profile
  checkGreenBG: require('../assets/images/check_green_bg.png'),
  editButton: require('../assets/images/edit_button.png'),

  radioUnSelectGreen: require('../assets/images/uncheck_no_tick.png'),
  radioSelectGreen: require('../assets/images/check_green_tick.png'),
  menuClose: require('../assets/images/menu_close.png'),

  // create challenge
  swapTeam: require('../assets/images/swap_team.png'),
  radioCheckGreenBG: require('../assets/images/radio_check_green_bg.png'),

  // Message Module
  messageCamera: require('../assets/images/messageCamera.png'),
  sendButton: require('../assets/images/sendButton.png'),
  groupUsers: require('../assets/images/groupUsers.png'),
  plus_round_orange: require('../assets/images/plus_round_orange.png'),
  leave_chat_room: require('../assets/images/leave_chat_room.png'),
  soccerBackground: require('../assets/images/soccerBackground.png'),
  firstVSTeam: require('../assets/images/firstTeam.png'),
  secondVSTeam: require('../assets/images/secondTeam.png'),
  warningIcon: require('../assets/images/warning.png'),
  popupUpArrow: require('../assets/images/topPopupArrow.png'),
  assistBy: require('../assets/images/assistBy.png'),
  blankRatingStar: require('../assets/images/blankRatingStar.png'),
  yellowRatingStar: require('../assets/images/yellowRatingStar.png'),
  blueRatingStar: require('../assets/images/blueRatingStar.png'),
  greenRatingStar: require('../assets/images/greenRatingStar.png'),
  moveFlottyButton: require('../assets/images/move_flotty_btn.png'),

};

export default images;
