const strings = {
  townsCupTitle: 'TOWNSCUP',
  alertmessagetitle: 'Towns Cup',
  defaultError: 'Something went wrong',
  titleBasic: 'Townscup',
  townsCupTagLine: 'All teams in the world.',
  welCome: 'Welcome',
  welcomeText: 'You\'re only a few steps away from joining Townscup.',
  fbText: 'Continue with Facebook',
  googleText: 'Continue with Google',
  signUpText: 'Signup with email',
  alreadyMember: 'Already a member yet? Log In',
  loginText: 'Log in',
  orText: 'OR',
  emailPlaceHolder: 'Email',
  allDay: 'All day',
  all: 'All',
  starts: 'Starts',
  ends: 'Ends',
  until: 'Until',
  weekly: 'Weekly',
  addTime: 'Add time',
  setAvailable: 'Set available',
  block: 'Block',
  thisEvent: 'This event',
  assistRefereeTitle: 'Assistant Referee',
  thisAndFollowingEvent: 'This and all following events',
  recurringEventTitle: 'Update Recurring Event',
  selectTimePlaceholder: 'Select Repeat',
  addressPlaceholder: 'Address',
  positionPlaceholder: 'Position',
  birthDatePlaceholder: 'Birthday',
  AppearancePlaceholder: 'Appearance',
  writeNotesPlaceholder: 'Notes',
  writedownRulesPlaceholder: 'Write down the rules',
  enterEmailPlaceholder: 'Enter your email address',
  passwordPlaceHolder: 'Password',
  forgotPassword: 'Forgot Password?',
  checkEmailText: 'Please check your e-mail',
  checkEmailDescText: 'We have sent you an email with a link to reset your password. It may take a few minutes for you to receive it.',
  signTerms:
    'By continuing you agree to Towny\'s Terms of Service, We will manage information about you as described in our PrivacyPolicy and Cookie Policy.',
  resetText: 'Reset your password.',
  nextTitle: 'NEXT',
  confirmAndPayTitle: 'CONFIRM AND PAY',
  applyTitle: 'APPLY',
  cancelTitle: 'CANCEL',
  doneTitle: 'DONE',
  saveTitle: 'SAVE',
  moveTitle: 'MOVE',
  loginCapTitle: 'LOGIN',
  continueCapTitle: 'CONTINUE',
  signUpCapitalText: 'SIGN UP',
  fnameText: 'First Name',
  lnameText: 'Last Name',
  nameText: 'Name',
  save: 'Save',
  done: 'Done',
  yes: 'Yes',
  passwordText: 'Password (at least 8 characters)',
  confirmPasswordText: 'Confirm Password',

  awaitingPayment: 'Awaiting Payment',
  pendingPayment: 'pendingpayment',
  requestSent: 'Request Sent',
  offered: 'offered',
  chiefReferee: 'CHIEF REFEREE',
  cancelled: 'cancelled',
  Cancelled: 'Cancelled',
  requestCancelled: 'requestcancelled',
  reqCan: 'Request Cancelled',
  accepted: 'accepted',
  Accept: 'Confirmed',
  declined: 'declined',
  Decline: 'Declined',

  infoTitle: 'Info',
  recentMatchTitle: 'Recentest Match',
  aboutRatingTitle: 'Detail info about ratings',
  refereeRecentMatchTitle: 'Recentest Refereed Match',
  reviewsTitle: 'Reviews',
  upcomingMatchTitle: 'Upcoming Match',
  statsTitle: 'Stats',
  signedUpTime: 'Signed up in 2020',
  infoTeamTitle: 'Vancouver Teams FC',
  infoTeamCity: 'Vancouver, BC',
  ntrpTitle: 'NTRP',
  refereeFee: 'Referee Fee',
  cancellationPolicy: 'Cancellation Policies',
  gameFee: 'Game Fee',
  perHour: ' (per hours)',
  ntrpSubTitle: ' (The national tennis rating program)',
  homePlaceTitle: 'Home place',
  homePlaceValue: 'BC Place 2059 W 4th Ave, Vancouver, BC, V6J 1M7',
  clubTeamTitle1: 'New York City FC',
  clubTeamCity1: 'New york, NY',
  clubTeamTitle2: 'Chelsea FC',
  clubTeamTitle3: 'FC Barcelona',
  leagueTeamTitle: 'UEFA Champions League',

  locationText: 'Your Location',
  locationPlaceholderText: 'Search city or postal code',
  sportText: 'Select your favourite sports.',

  // Add Birthday screen
  addBirthdayText: 'Add your birthday.',
  notDisplayText: 'This won’t be displayed on your public profile.',
  whyAskingText: 'Why is TownsCup asking for my birthday?',
  birthdatText: 'You must be at least 13 years old to have a TownsCup account in most countries.\n\nIf account represents someone under the age of 13, the user must clearly state in the account’s bio that the account is managed by a parent or manager.\n\nThis information also helps TownsCup provide age-appropriate services to its users. Furthermore, this information is required when you join a group or sports game which has age requirements in the TownsCup Community.',

  // Choose gender screen
  addGenderText: 'Add your gender.',
  notDisplayGenderText: 'This won’t be displayed on your public profile.',
  whyAskingGenderText: 'Why is TownsCup asking for my gender?',
  genderText: 'This information helps TownsCup provide gender-appropriate services to its users. Furthermore, this information is also required when you join a group or sports game which has gender-requirement in the TownsCup community.',
  maleRadioText: 'Male',
  femaleRadioText: 'Female',
  otherRadioText: 'Other',

  // CreateTeam Screen 1
  star: '*',
  newText: 'new',
  SportsTextFieldTitle: 'Sports',
  selectSportPlaceholder: 'Choose a Sport',
  teamNameTitle: 'Team Name',
  teamNamePlaceholder: 'Enter Team Name',
  playerTitle: 'Players',
  player1Title: 'Player 1',
  player2Title: 'Player 2',
  searchHereText: 'Search here',
  searchText: 'Search',
  genderTitle: 'Member\'s Gender',
  curruencyType: 'Currency Type',
  feeCyclePlaceholder: 'Fees cycle',
  selectCode: 'Country Code',
  selectGenderPlaceholder: 'Select Gender',
  selectCurruencyTypePlaceholder: 'Select Currency Type',
  membersAgeTitle: 'Member\'s Age',
  maxPlaceholder: 'Max',
  minPlaceholder: 'Min',
  locationTitle: 'Location',
  currentCity: 'Home City',
  birthdateText: 'Choose Date of birth',
  searchCityPlaceholder: 'Search by city or postal code',
  cityText: 'City',
  stateText: 'State',
  countryText: 'Country',
  postalCodeText: 'Postal Code/Zip',
  requiredText: 'required',
  clubBelongText: 'The created team will belong to',
  clubText: 'Club',
  // CreateTeam Screen 2

  membershipTitle: 'Membership',
  whoJoinTitle: 'Who can join the team?',
  membershipRequestText:
    'A person whose membership request has been accepted by a team admin',
  inviteText: 'Invite only',
  canNotChangeServing: 'You can not change serving player during game.',
  // Create Team screen 3

  registerTitle: 'Registration Fee',
  registerSubTitle:
    'A team admin can send a new member the invoice for the registration fee after the member joins your team.',
  basicFeeTitle: 'Basic Fee',
  enterFeePlaceholder: 'Enter fee',
  feeDetailsText: 'Fee Details',
  feeDetailsPlaceholder: 'Write Details regarding the registration fee…',
  membershipFeeTitle: 'Membership Fee',
  membershipSubTitle:
    'A team admin can send a member the invoice for the membership fee regularly.',
  membershipPlaceholder: 'Write Details regarding the membership fee…',

  // CreateTeam Screen 4
  matchFeeTitle: 'Match fee',
  matchFeeSubTitle:
    'When your team accepts a game reservation request from another team and plays a game against the team, the team will pay your team the below amount of the match fee. It may be refunded when the game is canceled.',
  cancellationPolicyTitle: 'Cancellation Policies',
  cancellationpolicySubTitle:
    'Please, choose one the cancellation policies below',
  strictText: 'Strict',
  moderateText: 'Moderate',
  flexibleText: 'Flexible',
  requesterWarningText:
    '*Requester: The team or person who sends the game reservation request initialy *Requestee: The team or person who receives the game reservation request initialy',
  strictPoint1Title: '-Cancellation 7 days in advance -',
  strictPoint2Title: '-Cancellation less than 7 days in advance -',
  strictPoint1Desc:
    'The challenge sender can cancel the game reservation up to 7 days before the game starting time and get a 50% refund, but not service fee. If only 50% of the reservation has been paid, no refund will be issued and the remaining 50% will simply not be charged.',

  strictPoint2Desc:
    'If the challenge sender cancels less than 7 days before the game starting time the game fee and service fee are not refunded.',

  moderatePoint1Title: '-Cancellation 14 days in advance-',
  moderatePoint2Title: '-Cancellation less than 14 days in advance-',
  moderatePoint3Title: '-Cancellation less than 24 hours in advance-',
  moderatePoint1Desc:
    'Free cancellation until 14 days before the game starting time.',
  moderatePoint2Desc:
    'The challenge sender can cancel less than 7 days before the game starting time and get a 50% refund, but not service fee. If only 50% of the reservation has been paid, no refund will be issued and the remaining 50% will simply not be charged.',
  moderatePoint3Desc:
    'If the challenge sender cancels less than 24 hours before the game starting time the game fee and service fee are not refunded.',
  flexiblePoint1Title: '-Cancellation 24 hours in advance-',
  flexiblePoint2Title: '-Cancellation less than 24 hours in advance-',
  flexiblePoint1Desc:
    'Free cancellation until 24 hours before the game starting time.',
  flexiblePoint2Desc:
    'If the challenge sender cancels less than 24 hours before the game starting time the game fee and service fee are not refunded.',

  // CreateClub Screen 1
  clubNameTitle: 'Club Name',
  clubNameplaceholder: 'Enter Club Name',

  // CreateClub Screen 2
  inviteTitle: 'Invitation to Membership',
  userText: 'USER',
  userSubtitle: 'Does a user need an invitation from the club to join It?',
  noUserText: 'No, a user doesn’t.',
  yesUserText: 'Yes, a user does.',
  teamText: 'TEAM',
  teamSubTitle: 'Does a user need an invitation from the club to join It?',
  noTeamText: 'No, a team doesn’t.',
  yesTeamText: 'Yes, a team does.',
  approvalTitle: 'Approval for Membership request',
  approvalUserSubTitle:
    'Does a user need the approval for his or her membership request from the club to join it?',
  approvalTeamSubTitle:
    'Does a user need the approval for its membership request from the club to join it?',
  whoJoinText: 'Who can join the club?',
  everyoneText: 'Everyone and Every team',
  onlyPersonText: 'Only person or team invited by club',
  whoseApprovalText:
    'Whose approval does an applicant need when joining the club?',
  noneText: 'None',
  clubAdminText: 'A club admin',
  inviteUserText: 'Invite user to club',
  goToClubText: 'Go to club home',
  // Register Player Screen
  sportsEventsTitle: 'Sport',
  descriptionText: 'Description',
  opetionalText: '(Optional)',
  descriptionPlaceholder: 'Describe yourself as a personal player',
  matchFeesTitle: 'Match Fee',
  perHourText: '(per hour)',
  configureEmailText: 'Can not open mail composer, please setup mail account from seting',

  // Register Referee Screen
  certificateTitle: 'Certificates',
  addCertiTitle: 'Add a Certificate',
  addCertiMainTitle: 'Please add the certificates or documents showing your professional experience.',
  descriptionRefereePlaceholder: 'Describe yourself as a referee',
  certificateSubTitle:
    'Please add the certificates or documents showing your professional experience.',
  addCertificateTitle: ' + Add a Certificate',
  languageTitle: 'Language',
  languagePlaceholder: 'Select Language',
  refereeFeesTitle: 'Referee Fee',
  deleteTitle: 'Delete',
  titleOrDescriptionText: 'Title or Description',
  title: 'Title',
  titlePlaceholder: 'Enter Title',
  createTitleValue: 'Welcome Season Party',
  titleValue: 'Games with Vancouver Whitecaps',
  about: 'Description',
  aboutPlaceholder: 'Enter Description',
  createAboutValue: 'I love playing soccer, Association football, commonly known as football or soccer, [a] is a sport played between seven teams of eleven with a spherical ball.',
  aboutValue: 'I love playing soccer, Association football, more commonly known as football or soccer, [a] is a team sport played between seven teams of eleven players with a spherical ball.',
  eventColorTitle: 'Event Color',
  eventCreatedTitle: 'Events Created By You',
  groupEventTitle: 'The events of which group do you want to be displayed in your schedule?',
  eventImportedTitle: 'Event Imported From Other Groups',
  games: 'Games',
  scheduleMatchTitle: 'Scheduled Matches',
  timeTitle: 'Time',
  from: 'From',
  fromTime: 'Feb 15, 2019 1:00 am',
  date: 'Jan 25, 2019',
  time: '12:00 am',
  to: 'To',
  repeat: 'Repeat',
  repeatTime: 'Weekly \n(Until Mar 25, 2019 12:00 am)',
  place: 'Place',
  placeName: '800 Griffiths Way, Vancouver, BC V6B 6G1',
  availableTitle: 'Challenge Availability',
  scheduleTitle: 'Schedule',
  whoCanSeeShcedule: 'Who can see your schedule?',
  availableSubTitle: 'Do you want to set the time to be available to receive a challenge request during this event?',
  available: 'Available',
  blocked: 'Blocked',
  editChallengeTitle: 'Set the time to be available to receive a challenge request or block it.',

  // Group setting & Privacy
  connectionTitle: 'Connetions',
  whoCanSeeClub: 'Who can see members in club connections?',
  whoCanSeeTeam: 'Who can see members in team connections?',
  whoCanSeeClubFollowers: 'Who can see followers in club connections?',
  whoCanSeeTeamFollowers: 'Who can see followers in team connections?',
  everyoneRadio: 'Everyone',
  followersRadio: 'Followers',
  clubMembersRadio: 'Club Members',
  adminsRadio: 'Only Club & Team Admins',

  // Change password
  oldPassword: 'Current Password',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  atLeastText: '(At least 8 characters)',

  // reservation

  doneByText: 'Done by',
  detailText: 'DETAILS',
  respondWithinText: 'RESPOND',
  noReservationFountText: 'No Reservations Found',
  // member connection
  connectAccountText: 'Invite or Connect Account',
  connectProfile: 'Connect the profile to this account',
  sendInvite: 'Send invitation to this e-mail account',
  connectMemberProfile: 'Connect this member to profile',
  createOtherProfile: 'Create another member profile',
  goToMemberProfile: 'GO TO MEMBERS',
  enterFirstNamePlaceholder: 'Enter First Name',
  firstName: 'First Name',
  lastName: 'Last Name',
  enterLastNamePlaceholder: 'Enter Last Name',
  enterBioPlaceholder: 'Enter Your Biography',
  enterAboutPlaceholder: 'Enter Your About',

  inviteEmailText: 'Please enter the e-mail account of the person that you want to invite.',
  inviteSearchText: 'Who do you want to invite to your team?',
  addEmailText: '+ Add E-Mail',
  addPhone: '+ Add Phone',
  addPosition: '+ Add Position',
  camera: 'Camera',
  album: 'Album',
  editprofiletitle: 'Edit Profile',
  slogan: 'Slogan',
  enterSloganPlaceholder: 'Enter Your Slogan',
  invitationSent: 'Invitation sent',
  userNotFoundByEmail: 'We didn’t find a user whose e-mail account is',
  jerseyNumberPlaceholder: 'Jersey Number',

  abouttitle: 'About',
  basicinfotitle: 'Basic Info',
  teamstitle: 'Teams',
  clubstitle: 'Clubs',
  leaguesTitle: 'League',
  signedupin: 'Signed up in ',
  editabouttitle: 'Edit About',
  editbasicinfotitle: 'Edit Basic Info',
  birth: 'Birth',
  yearOfBirth: 'Year of Birth',
  gender: 'Gender',
  phone: 'Phone',
  mostUsedFoot: 'Most Used Foot',
  currrentCityTitle: 'Current City',
  height: 'Height',
  weight: 'Weight',
  heightplaceholder: 'Enter Your Height',
  weightplaceholder: 'Enter Your Weight',
  playin: 'Plays In',
  refereesin: 'Referees In',
  scorekeeperIn: 'Scorekeeper In',
  totalGames: 'game',
  message: 'Message',
  follow: 'Follow',
  following: 'Following',
  invite: 'Invite',
  member: 'Member',
  join: 'Join',
  joining: 'Joining',
  challenge: 'Challenge',

  // Message
  noMessageFountText: 'No Message Found',

  other: 'other',
  others: 'others',
  and: 'and',

  pendingrequests: 'Pending Requests',
  today: 'Today',
  earlier: 'Earlier',

  trashmessage: 'Notifications in trash will be permanently deleted 30 days after they are moved in trash.',
  left: 'left',
  responsetime: '* Response time :',
  responsetimeexpired: 'RESPONSE PERIOD EXPIRED',
  decline: 'DECLINE',
  accept: 'ACCEPT',
  calcelRequest: 'CANCEL REQUEST',
  cancelAlterRequest: 'CANCEL ALTERATION REQUEST',
  cancelMatch: 'CANCEL MATCH',
  cancelreservation: 'CANCEL RESERVATION',
  alterReservation: 'CHANGE RESERVATION',
  sendAlterRequest: 'SEND ALTERATION REQUEST',
  cancel: 'Cancel',
  goToGameHome: 'GO TO GAME HOME',
  alreadyjoinclubmessage: 'Your team can’t join this club because a team can join only a club.',
  isinvitedsuccesfully: 'is invited successfully',

  bioPrivacyTitle: 'Who can see Bio?',
  basicInfoPrivacyTitle: 'Who can see each category in Basic Info?',
  ntrpPrivacyTitle: 'Who can see NTRP?',
  homePlacePrivacyTitle: 'Who can see Home Place?',
  teamPrivacyTitle: 'Who can see Teams?',
  clubPrivacyTitle: 'Who can see Clubs?',
  leaguePrivacyTitle: 'Who can see Leagues?',
  certiPrivacyTitle: 'Who can see Certificates?',
  refereeFeePrivacyTitle: 'Who can see Referee Fee?',

  bio: 'Bio',
  contact: 'Contact',
  website: 'Website',
  emailtitle: 'Email',
  office: 'Office',
  homefield: 'Home Field',
  NA: 'n/a',
  addwebsite: 'Add Website',
  addemail: 'Add Email',
  addphone: 'Add Phone',
  addoffice: 'Add Office',
  addhomefield: 'Add Home Field',
  editcontact: 'Edit Contact',
  editbio: 'Edit Bio',
  enterwebsite: 'Enter Website',
  enteremail: 'Enter Email',
  enterphonenumber: 'Enter Phone Number',
  officeaddress: 'Office Address',
  homeaddress: 'Home Address',
  membersTitle: 'Members',
  sport: 'Sport',
  hometown: 'Home town',
  membersgender: 'Member\'s gender',
  membersage: 'Member\'s age',
  language: 'Language',
  languagesName: 'Korean, English, Hindi, Italian',
  membershipregfee: 'Membership registration fee',
  membershipfee: 'Membership Fee',
  CADpermatch: 'CAD / MATCH',
  addaddress: 'Add Address',
  addbirth: 'Add Birthday',
  addgender: 'Add Gender',
  addheight: 'Add Height',
  addweight: 'Add Weight',
  gamefeetitle: 'Game Fee',
  perhoursinbracket: '(per hours)',
  gamefeeperhour: 'Game Fee Per Hour',
  CAD: 'CAD',
  currencyplacholder: 'Select Currency',
  languages: 'Languages',
  sportcannotbeblank: 'Sports cannot be blank',
  week: 'week',
  biweek: 'biweek',
  month: 'month',
  year: 'year',
  bylaw: 'Bylaw',
  editbylaw: 'Edit Bylaw',
  enterBylawPlaceholder: 'Enter Bylaw',
  leagues: 'Leagues',
  tcpoint: 'TC Points',
  tcranking: 'TC Ranking',
  history: 'History',
  addrole: 'Add Role',
  addPlaying: 'Add playing',
  addRefereeing: 'Add refereeing',
  addScorekeeping: 'Add scorekeeping',
  cards: 'Cards',
  addcard: 'Add New Card...',
  endingin: ' ****',
  addacard: 'Add a Card',
  entergamefee: 'Enter Game Fee',
  matchfee: 'Match fee',
  refereeFeecardText: 'Referee fee',
  scorekeeperFee: 'Scorekeeper fee',
  firstnamevalidation: 'First name cannot be blank',
  lastnamevalidation: 'Last name cannot be blank',
  locationvalidation: 'Location cannot be blank',
  addOptionMessage: '+ Add a payment method',
  selectPaymentText: 'Please select payment method.',
  selectPaymentMethod: 'Select a payment method',
  cannotAcceptText: 'Reservation can not be change after game has been started.',
  refereeOfferExpiryText: 'Offer expired or game start time already passed.',
  selectCardText: 'Please select payment method.',
  reservationRequestSent: 'SENT',
  reservationRequestPending: 'PENDING',
  reservationConfirmed: 'CONFIRMED',
  reservationDeclined: 'DECLINED',
  alterationRequestSent: 'ALTERATION REQUEST SENT',
  alterationRequestPending: 'ALTERATION REQUEST PENDING',
  reservationCancelled: 'CANCELLED',
  reservationRestored: 'RESTORED',
  reservationAwaitingPayment: 'AWAITING PAYMENT',
  alterationRequestCancelled: 'ALTERATION REQUEST CANCELLED',
  challenger: 'Challenger',
  challengee: 'Challengee',
  requester: 'Requester',
  requestee: 'Requestee',

  // reservation request

  reservationRequestAccepted: 'Reservation request accepted',
  reservationRequestDeclined: 'Reservation request declined',
  reservationRequestCancelled: 'Reservation request cancelled',
  reservationRequestRestored: 'Reservation request restored',

  reservationAlterRequestAccepted: 'Alteration request accepted',
  reservationAlterRequestDeclined: 'Alteration request declined',
  reservationAlterRequestCancelled: 'Alteration request cancelled',

  gameHomeText: 'GAME HOME',
  restorePreviousText: 'RESTORE TO PREVIOUS VERSION',
  tryToPayText: 'TRY TO PAY AGAIN',

  sportAlreadyRegisterd: 'This sport already registerd.',
  choosePayment: 'Please choose payment method.',
  chooseFutureDate: 'Please choose future date for challenge.',
  chooseCorrectDate: 'Please choose correct date and time.',
  max5Referee: 'Maximum 5 referees can be added.',
  max5Scorekeeper: 'Maximum 5 scorekeeper can be added.',
  serchByLocation: 'Search by address',
  cannotChangeReservationText: 'Reservation can not be change after game has been started.',
  cannotChangeReservationGameStartedText: 'Reservation can not be change after game time has beed expired or offer expired.',
  cannotCancelReservationText: 'Reservation cannot be cancel after game time passed or offer expired.',
  selectSetText: 'Select sets',
  selectNumberOfGameText: 'Select number of games',
  gameScoreText: 'Select game score',
  selectWiningPoints: 'Select wining points',
  selectPointsText: 'Select points',
  selectAnyCard: 'Please any of the card.',
  networkConnectivityErrorMessage: 'Could not connect to the internet. Please check your network',
  recentPointDelete: 'The recentest won point will be canceled.',
  noWonPoint: 'Score not added yet.',
  gameNotStarted: 'Game not started yet.',
  gamePaused: 'Game is paused.',
  gameEnded: 'Game is ended.',
  selectTeam: 'Please Select Team',
  resetMatchRecord: 'Do you want to reset all the match records?',
  reviewForTeams: 'Review for Teams',
  reviewForPlayers: 'Review for Players',
  reviewForReferees: 'Review for Referees',
  editReviewForTeams: 'Edit Review for Teams',
  completeReviewFirst: 'Please, complete all ratings before moving to the next.',
  punchualityDesc: 'Did the the referee arrive at the match place on time?',
  punchualityDescScorekeeper: 'Did the the scorekeeper arrive at the match place on time?',
  chooseTeamFirst: 'Please choose any one team for review.',
  descriptionScorekeeperPlaceholder: 'Describe yourself as a scorekeeper',
  editReviewText: 'EDIT REVIEW FOR A TEAM',
  leaveReviewText: 'LEAVE REVIEW FOR A TEAM',
  leaveOrEditReviewText: 'LEAVE OR EDIT YOUR REVIEW',
  bookReferee: 'BOOK REFEREE',
  bookScorekeeper: 'BOOK SCOREKEEPER',
  refereeRequestScreenTitle: 'Referee Reservation Request',
  refereeScreenTitle: 'Referee Reservation',

  scorekeeperRequestScreenTitle: 'Scorekeeper Reservation Request',
  scorekeeperScreenTitle: 'Scorekeeper Reservation',
  chooseScorekeeperText: 'Choose a scorekeeper',

  privacySettings: 'Privacy Settings',
  gameEndedAlertText: 'Game is ended, so you can not change reservation.',
  enterValidGameFee: 'Please enter valid game fee.',
  whatsGoingText: 'What\'s going on?',
  writeText: 'Please write some text or select any image.',
  cannotCancelReservationAfterGameStartText: 'Reservation cannot be cancel after game game has beed started.',
cannotChooseDatetime: 'This datetime is overlapping with blocked datetime.',
recentMatchesTitle: 'Recent Matches',
upcomingMatchesTitle: 'Upcoming Matches',
lookingForTitle: 'Looking for a challenger',
shortsTitle: 'Shorts',
hiringPlayerTitle: 'Hiring players',
lookingForTeamTitle: 'Looking for a team',
refereesTitle: 'Referees',
scorekeeperTitle: 'Scorekeepers',
searchTitle: 'Search by city, state or country',
challengeeSecureText: 'The challengee secures the match place',
challengerSecureText: 'The challenger secures the match place',
recentMatchPlaceholderText: 'There are no recent games.\nWould you like to start your game?',
upcomingMatchPlaceholderText: 'There is no Upcoming Match.\nWould you like to start your challenge?',
challengerPlaceholderText: 'There is no challenge.\nWould you like to start your challenge?',
hiringPlayersPlaceholderText: 'There is no Hiring team.\nWould you like to start to hire players?',
lookingTeamsPlaceholderText: 'There is no Player.\nWould you like to start registering players?',
refereesPlaceholderText: 'There is no referee.\nWould you like to start registering Referees?',
scorekeepersPlaceholderText: 'There is no Scorekeeper.\nWould you like to start registering\nScorekeeper?',

};
export default strings;
