const Verbs = {
  entityTypeGame: 'game',
  entityTypeClub: 'club',
  entityTypeClubs: 'clubs',
  entityTypeTeam: 'team',
  entityTypeTeams: 'teams',
  entityTypeLeague: 'league',
  entityTypeUser: 'user',
  entityTypePlayer: 'player',
  entityTypePlayers: 'players',
  entityTypeGroups: 'groups',
  entityTypeUsers: 'users',
  entityTypeReferee: 'referee',
  entityTypeScorekeeper: 'scorekeeper',
  entityTypeOpponent: 'opponent',

  tennisSport: 'tennis',
  doubleSport: 'double',
  singleSport: 'single',
  tennisSingleSport: 'Tennis Singles',
  tennisDoubleSport: 'Tennis Double',
  privacyTypeEveryone: 'everyone',
  privacyTypeFollowers: 'followers',
  privacyTypeMembers: 'members',
  privacyTypeAdmins: 'admins',
  sportType: 'sport',
  locationType: 'location',
  open: 'open',
  paid: 'paid',
  norefund: 'norefund',
  refundStatus: 'refund',
  allStatus: 'All',
  male: 'male',
  female: 'female',
  otherVerb: 'other',
  on: 'On',
  off: 'Off',
  acceptVerb: 'accept',
  declineVerb: 'decline',
  cancelVerb: 'cancel',
  restoredVerb: 'restored',
  winnerVerb: 'winner',
  drawVerb: 'draw',
  looserVerb: 'looser',
  followVerb: 'follow',
  unfollowVerb: 'unfollow',
  inviteVerb: 'invite',
  bothVerb: 'both',
  messageVerb: 'message',
  editVerb: 'edit',
  joinVerb: 'join',
  leaveVerb: 'leave',
  leaveTeamVerb: 'leaveTeam',
  joinTeamVerb: 'joinTeam',
  dotVerb: 'dot',
  followingVerb: 'following',
  eventVerb: 'event',
  blockedVerb: 'blocked',
  unpauseVerb: 'unpause',
  reactivateVerb: 'reactivate',
  pauseVerb: 'pause',
  deactivateVerb: 'deactivate',
  challengeVerb: 'challenge',
  allVerb: 'All',
  soccer: 'Soccer',
  todayVerb: 'Today',
  tomorrowVerb: 'Tomorrow',
  futureVerb: 'Future',
  challenge: 'Challenge',
  reservation: 'Reservation',
  usd: 'USD',
  cad: 'CAD',
  strictText: 'Strict',
  moderateText: 'Moderate',
  flexibleText: 'Flexible',
  card: 'card',
  friendly: 'Friendly',
  official: 'Official',
  comment: 'comment',
  like: 'like',
  unlike: 'unlike',
  reply: 'reply',
  screenTypeModal: 'modal',
  screenTypeMainScreen: 'mainScreen',
  eventRecurringEnum: {
    Never: 0,
    Daily: 1,
    Weekly: 2,
    WeekOfMonth: 3,
    DayOfMonth: 4,
    WeekOfYear: 5,
    DayOfYear: 6,
  },
  gpsErrorDeined: 'gpsErrorForDenied',

  sportTypeSingle: 'single',
  sportTypeDouble: 'double',
  sportTypeTeam: 'team',

  countTypeRatio: 'Ratio',
  countTypeSets: 'Sets',
  countTypeTime: 'Time',
  requestVerb: 'request',
  menuOptionTypePlaying: 'Playing',
  menuOptionTypeRefereeing: 'Refereeing',
  menuOptionTypeScorekeeping: 'Scorekeeping',

  PRIVACY_GROUP_MEMBER_EVERYONE: 0,
  PRIVACY_GROUP_MEMBER_FOLLOWER: 1,
  PRIVACY_GROUP_MEMBER_TEAMMEMBERS: 2,
  PRIVACY_GROUP_MEMBER_CLUBMEMBERS: 3,
  PRIVACY_GROUP_MEMBER_TEAM: 4,
  PRIVACY_GROUP_MEMBER_CLUB: 5,
  PRIVACY_GROUP_MEMBER_TEAMCLUB: 6,

  allText: 'all',
  homeText: 'home',
  awayText: 'away',
  setText: 'Set',
};

export default Verbs;
