require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'townscup_reactnative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNTextGradientView', :path => '../node_modules/react-native-text-gradient'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'

  target 'townscup_reactnativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'townscup_reactnative-tvOS' do
  # Pods for townscup_reactnative-tvOS

  target 'townscup_reactnative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
