require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
project 'Townscup',
        'Debug' => :debug,
        'Release' => :release, 
        'Debug_Development' => :debug,
        'Release_Development' => :release,
        'Debug_QA' => :debug, 
        'Release_QA' => :release,
        'Debug_Staging' => :debug, 
        'Release_Staging' => :release,
        'Debug_Production' => :debug, 
        'Release_Production' => :release
target 'townscup_reactnative' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'RNTextGradientView', :path => '../node_modules/react-native-text-gradient'
  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  target 'townscup_reactnativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
  # use_flipper!({'Flipper' => '0.87.0' , 'Flipper-Folly' => '2.5.3' , 'Flipper-RSocket' => '1.3.1' })
  #   post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'townscup_reactnative-tvOS' do
  # Pods for townscup_reactnative-tvOS

  target 'townscup_reactnative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
